### ISSUE TITLE
the released binary CKB client file size is a bit large

### ISSUE THREAD

**Issue by liushooter** [nervosnetwork/ckb#1005]
https://github.com/nervosnetwork/ckb/commit/d21788f334251e0eae3241d5a0e11c6ab464248c

```
[profile.release]
debug = true
```

**Comment by doitian** [comment]
The project is in an early stage, we need to package the symbol table to ease locating bugs.

**Comment by doitian** [comment]
Closed by https://github.com/nervosnetwork/ckb/issues/1008
