### ISSUE TITLE
CKB miner has been runing for a few days but not a single transaction of mine can be searched on CKB explorer

### ISSUE THREAD

**Issue by huanglilei** [nervosnetwork/ckb#1038]
**Describe the bug**
I've beening mining CKB on ckb testnet for a few days with my MacBook Pro, but still can't find a single tx on CKB explorer. Is my machine too powerless or there is something i missed? Some suggestions on debugging this case is very appreciated!
 

**To Reproduce**
I strictly followed tutorial on https://docs.nervos.org, setup everything and ran miner with ckb node running

**Screenshots**
![image](https://user-images.githubusercontent.com/16791744/59562345-02cfa900-905e-11e9-8e2e-6b06f451cd3e.png)
![image](https://user-images.githubusercontent.com/16791744/59562393-bafd5180-905e-11e9-9495-0a19d5d2f9b7.png)

**Environment**
 - OS: MacOS 
 - Version 10.14

**Additional context**
none

**Comment by driftluo** [comment]
On June 15th, the test network cut to 0.14. From your log, you seem to be still in version 0.13.

0.13 of the data has been emptied, so you can't find any data.

**Comment by huanglilei** [comment]
So it there anything i could do to follow upgrades of test network? I run `ckb run` a few minutes ago and the block height is still growing on old height:
![image](https://user-images.githubusercontent.com/16791744/59562524-4b886180-9060-11e9-82ab-1f9a0fbec6d6.png)

**Comment by driftluo** [comment]
0.13 is not compatible with 0.14. You need to download the [binary](https://github.com/nervosnetwork/ckb/releases) of 0.14.1 or compile it yourself, then delete the data of 0.13 (xx/data).

Regenerate the configuration and start syncing. `args` on ‘ckb.toml’ can be used with 0.13 same parameters, but `code_hash` has been modified, **please note here**

**Comment by huanglilei** [comment]
thx, i'll give a try
