### ISSUE TITLE
sending loads of txs but parts failed

### ISSUE THREAD

**Issue by kellyshang** [nervosnetwork/ckb#1082]
**Environment**

- **CKB version**: [CKB Testnet v0.14.1]
- **Chain**: Testnet
- **Operating system**: Win10
- **Arch**: x64
- **Installation**: GitHub Release

**Describe the bug**
pre transaction: 0xce1a92406d4f0b313f402fb9c8f12874713e66aecf9283ebcb401d090ed4e41b
1. try to sending 400 txs using rpc with the cells of same tx_hash but different index, former 232 txs has been commited to the chain successfully and been packaged in blocks;
2. for index 233, send_transaction returns error response of "{"jsonrpc":"2.0","error":{"code":-3,"message":"InvalidTx(ScriptFailure(ValidationFailure(-3)))"},"id":2}";
3. for index 234, send_transaction returns error response of "{"jsonrpc":"2.0","error":{"code":-3,"message":"InvalidTx(ScriptFailure(ValidationFailure(-2)))"},"id":2}";
4. from index 235 and later on, send_transaction returns error response of "{"jsonrpc":"2.0","error":{"code":-3,"message":"InvalidTx(ScriptFailure(VMError(OutOfBound)))"},"id":2}"

[ckbloadtestlogs.txt](https://github.com/nervosnetwork/ckb/files/3312936/ckbloadtestlogs.txt)

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by doitian** [comment]
The generated transaction contains too many useless data in witnesses. Started from 233, the witnesses data size exceeds the limit 32k set in the `secp256k1_blake160_sighash_all`. This bug will be tracked in https://github.com/nervosnetwork/ckb-system-scripts/issues/22 . 

If you are using SDK to sign the transaction, please report a the bug to the corresponding SDK repository.
