### ISSUE TITLE
Wallet encryption

### ISSUE THREAD

**Issue by NedValY** [nervosnetwork/ckb#1110]
- No encryption method is provided to protect Personal Wallet in cli mode.
- Generally, in the case of a typical Bitcoin of POW, this wallet is encrypted by storing several utxo in one wallet.
- Nervos does not have such an encryption solution.
- If you have an account, you think it is necessary to encrypt the account file, like ethereum.

**Comment by TheWaWaR** [comment]
[ckb-cli](https://github.com/nervosnetwork/ckb-cli/tree/ckb-v0.15/ckb-sdk/src/wallet/keystore) already have a [Web3 V3 KeyStore](https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition) implementation, will include in next `ckb-cli` release.

The API will like this:
``` shell
# Create an account
$ ckb-cli account new
Your new account is locked with a password. Please give a password. Do not forget this password.
Password: xxx
Repeat Password: xxx
address:
  mainnet: ckb1q9gry5zgrw2z466afnhnk0afwf4mr4ljwjtfwkxzz82wmy
  testnet: ckt1q9gry5zgrw2z466afnhnk0afwf4mr4ljwjtfwkxzgmj52k
lock_arg: 1b942aeb5d4cef3b3fa9726bb1d7f274969758c2

# Enter interactive mode and transfer capacity to an address
$ ckb-cli
CKB> account unlock --lock-arg 1b942aeb5d4cef3b3fa9726bb1d7f274969758c2
Password: xxx
lock-after: "29 minutes, 59 seconds"
CKB> wallet transfer --from-lock-arg 1b942aeb5d4cef3b3fa9726bb1d7f274969758c2 --to-address ckt1q9gry5zge3td868xls3mjdrqzlkj4zgzuu0kqqp8kmmakq --capacity 666
<tx-hash>
```

**Comment by janx** [comment]
Thanks for your suggestion! The wallet component is still wip, please keep an eye on our next release.
