### ISSUE TITLE
Add a subcommand `ckb doctor` to do self check

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#1260]
For example:

- Verify config file
- Check data directory permission
- Check database version and genesis stored in the database

**Comment by zjhmale** [comment]
@doitian what is the spec of the config file and the genesis?

**Comment by doitian** [comment]
No. Currently, it depends on how the config is used.

**Comment by zjhmale** [comment]
Hmm, so what's the rule to verify the config file and the genesis info?

**Comment by zjhmale** [comment]
Hmm, so what's the rule to verify the config file and the genesis info?

**Comment by zjhmale** [comment]
ping @doitian
