### ISSUE TITLE
 ckb run  error  in windows 7, unknown variant `Assembly`

### ISSUE THREAD

**Issue by runrun88** [nervosnetwork/ckb#1391]
**Environment**

- **CKB version**: output of `ckb --version`
ckb 0.18.0 (rylai-v7 ccc3006c 2019-08-10)
- **Chain**: dev / testnet / ...
- **Operating system**: Linux / macOS / Windows
window 7  X64
- **Arch**: x64
- **Installation**: GitHub Release / Built from source

**Describe the bug**
Config Error: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, mess
age: "unknown variant `Assembly`, expected `Rust`", key: ["script", "runner"] }
}

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by doitian** [comment]
How do you generate `ckb.toml`. Do you copy it from other machines?

**Comment by doitian** [comment]
If you have a `ckb.toml` in the working directory, please upload it.

**Comment by runrun88** [comment]
# Config generated by `ckb init --chain testnet`

data_dir = "data"

[chain]
# Choose the kind of chains to run, possible values:
# - { file = "specs/dev.toml" }
# - { bundled = "specs/testnet.toml" }
spec = { bundled = "specs/testnet.toml" }

[logger]
filter = "info"
color = true
log_to_file = true
log_to_stdout = true

[sentry]
# set to blank to disable sentry error collection
dsn = "https://48c6a88d92e246478e2d53b5917a887c@sentry.io/1422795"
# if you are willing to help us to improve,
# please leave a way to contact you when we have troubles to reproduce the errors.
# org_contact = ""

[network]
listen_addresses = ["/ip4/0.0.0.0/tcp/8115"]
### Specify the public and routable network addresses
# public_addresses = []

# Node connects to nodes listed here to discovery other peers when there's no local stored peers.
# When chain.spec is changed, this usually should also be changed to the bootnodes in the new chain.
bootnodes = [
  # Hangzhou (China)
  "/ip4/47.111.169.36/tcp/8111/p2p/QmNQ4jky6uVqLDrPU7snqxARuNGWNLgSrTnssbRuy3ij2W",
  # Ohio (USA)
  "/ip4/18.217.146.65/tcp/8111/p2p/QmT6DFfm18wtbJz3y4aPNn3ac86N4d4p4xtfQRRPf73frC",
  # Singapore
  "/ip4/18.136.60.221/tcp/8111/p2p/QmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb",
  # London
  "/ip4/35.176.207.239/tcp/8111/p2p/QmSJTsMsMGBjzv1oBNwQU36VhQRxc2WQpFoRu1ZifYKrjZ",
]

### Whitelist-only mode
# whitelist_only = false
### Whitelist peers connecting from the given IP addresses
# whitelist_peers = []

max_peers = 125
max_outbound_peers = 8
# 2 minutes
ping_interval_secs = 120
# 20 minutes
ping_timeout_secs = 1200
connect_outbound_interval_secs = 15
# If set to true, try to register upnp
upnp = false
# If set to true, network service will add discovered local address to peer store, it's helpful for private net development
discovery_local_address = false
# If set to true, random cleanup when there are too many inbound nodes
# Ensure that itself can continue to serve as a bootnode node
bootnode_mode = false

[rpc]
listen_address = "127.0.0.1:8114"

# Default is 10MiB = 10 * 1024 * 1024
max_request_body_size = 10485760

# List of API modules: ["Net", "Pool", "Miner", "Chain", "Stats", "Indexer", "Experiment"]
modules = ["Net", "Pool", "Miner", "Chain", "Stats", "Experiment"]

[tx_pool]
max_mem_size = 20_000_000 # 20mb
max_cycles = 200_000_000_000
max_verfify_cache_size = 100_000

[script]
runner = "Rust"

[store]
header_cache_size       = 4096
cell_output_cache_size  = 128

# [alert_notifier]
# # Script will be notified when node received an alert, first arg is alert message string.
# notify_script = "echo"

# Set the lock script to protect mined CKB.
#
# CKB uses CS architecture for miner. Miner process (ckb miner) gets block
# template from the Node process (ckb run) via RPC. Thus the lock script is
# configured in ckb.toml instead of ckb-miner.toml, and the config takes effect
# after restarting Node process.
#
# The `code_hash` identifies different cryptography algorithm. Read the manual
# of the lock script provider about how to generate this config.
#
# CKB provides an secp256k1 implementation, it requires a hash on the
# compressed public key. The hash algorithm is blake2b, with personal
# "ckb-default-hash". The first 160 bits (20 bytes) are used as the only arg.
#
# You can use any tool you trust to generate a Bitcoin private key and public
# key pair, which can be used in CKB as well. CKB CLI provides the function for
# you to convert the public key into block assembler configuration parameters.
#
# Here is an example using OpenSSL to generate the key pair:
#
# **WARNING**: This command will print the private key to screen.
#
#    openssl ecparam -genkey -name secp256k1 -text -noout -outform DER | \
#       xxd -p -c 1000 | \
#       sed 's/41534e31204f49443a20736563703235366b310a30740201010420/PrivKey: /' | \
#       sed 's/a00706052b8104000aa144034200/\'$'\nPubKey: /'
#
# Once you get your public key, generate the block assembler parameters:
#
#     ckb cli secp256k1-lock <pubkey>
#
# The command `ckb init` also accepts options to generate the block assembler
# directly. See `ckb init --help` for details. And `ckb cli secp256k1-lock` can
# also prints the command line options for `ckb init`.
#
#     ckb cli secp256k1-lock <pubkey> --format cmd
#
# The two commands can be combined together:
#
#     ckb init $(ckb cli secp256k1-lock <pubkey> --format cmd)
#
# Also, ckb allows the miners to add any data to the cellbase that they have dug out.
# The data must be A 0x-prefixed hex string.
#
# note: The data field is optional.
#
# **WARNING**: if data is larger than the capacity value of the current cellbase,
# it will be truncated
#
# secp256k1_blake160_sighash_all example:
# [block_assembler]
[block_assembler]
code_hash = "0x94334bdda40b69bae067d84937aa6bbccf8acd0df6626d4b9ac70d4612a11933"
args = [ "0xb881129636ea1c6f8d63e913340d811449a2421f" ]

**Comment by runrun88** [comment]
> How do you generate `ckb.toml`. Do you copy it from other machines?

no ! 
ckb.toml has been generated from cbk init 。

**Comment by doitian** [comment]
Cannot reproduce. Could you provide the detailed steps to reproduce this from a clean installation?

**Comment by doitian** [comment]
This bug has been fixed long time ago. I'm afraid you are running an old version of ckb, or using a config file in other locations.

**Comment by doitian** [comment]
Runner config has been removed in the recent release.
