### ISSUE TITLE
How to get output address?

### ISSUE THREAD

**Issue by ruanqunfeng** [nervosnetwork/ckb#1438]
How much should the fee be set?

**Comment by doitian** [comment]
CKB use OutPoint to reference a transaction output internally. It consists of the transaction hash, and the index of the output in the transaction outputs array.

If you want to know the wallet address, that is generated from the lock script. See the [CKB address format RFC](https://github.com/nervosnetwork/rfcs/pull/100).

Miner will consider the fee when selecting transactions. If the network is congested, transactions with higher fee have a high probability to be selected. We are going to add an RPC to return the suggested fee based on the existing queued transactions in the pool.

**Comment by ruanqunfeng** [comment]
> CKB use OutPoint to reference a transaction output internally. It consists of the transaction hash, and the index of the output in the transaction outputs array.
> 
> If you want to know the wallet address, that is generated from the lock script. See the [CKB address format RFC](https://github.com/nervosnetwork/rfcs/pull/100).
> 
> Miner will consider the fee when selecting transactions. If the network is congested, transactions with higher fee have a high probability to be selected. We are going to add an RPC to return the suggested fee based on the existing queued transactions in the pool.

Thanks!!!
