### ISSUE TITLE
Hello, there has a question, how to get the ckb for test?

### ISSUE THREAD

**Issue by ruanqunfeng** [nervosnetwork/ckb#1446]
This is my testnet address : ckt1qyq9uq0sdahjt8zc4wqm47d88lf0rut4zatqp9q7sg

**Comment by ruanqunfeng** [comment]
![image](https://user-images.githubusercontent.com/15098545/63484850-aeb8c900-c4d3-11e9-8cfc-feb9b11d7595.png)
I run the ckb-miner, but no block mined

**Comment by classicalliu** [comment]
https://faucet.nervos.org
Have you tried faucet ?

**Comment by ruanqunfeng** [comment]
> https://faucet.nervos.org
> Have you tried faucet ?

No，Know for the first time.
Thanks
