### ISSUE TITLE
v0.19.0-rc1 ckb.toml hash_type description exist error

### ISSUE THREAD

**Issue by duanyytop** [nervosnetwork/ckb#1458]
**Environment**

- **CKB version**: v0.19.0-rc1
- **Chain**: dev / testnet / ...
- **Operating system**:  macOS 
- **Arch**: x64
- **Installation**: GitHub Release 

**Describe the bug**

When I want to run v0.19.0-rc1 from GitHub release, I find ckb.toml last line exists error

```
 # hash_type = "Hash type, could be Data or Type"
``` 

actual:  `# hash_type = "Hash type, could be Data or Type"`
expected:   `# hash_type = "Hash type, could be data or type"`

**Comment by doitian** [comment]
> Config Error: Error { inner: ErrorInner { kind: Custom, line: Some(133), col: 0, at: Some(4447), message: "unknown variant Type, expected data or type", key: ["block_assembler", "hash_type"] } }

**Comment by doitian** [comment]
Fixed in #1464
