### ISSUE TITLE
cannot run ckb node

### ISSUE THREAD

**Issue by qiluge** [nervosnetwork/ckb#1504]
I has config the block_assembler at ckb.toml followed https://docs.nervos.org/getting-started/run-node, then run the node. However, I got the error msg ```Config Error: Error { inner: ErrorInner { kind: Custom, line: Some(147), col: 0, at: Some(5138), message: "missing field `hash_type`", key: ["block_assembler"] } }```.

I find the example configure at ckb.toml like this:
```
[block_assembler]
code_hash = "0x68d5438ac952d2f584abf879527946a537e82c7f3c1cbf6d8ebf9767437d8e88"
args = [ "ckb cli blake160 <compressed-pubkey>" ]
data = "A 0x-prefixed hex string"
hash_type = "type"
```
please update your document about the cooresponding desription of ```data``` and ```hash_type``` field. And I would be very happy to see you explaining these field here.

**Comment by doitian** [comment]
- The ckb.toml has a large paragraph about this config.
- `hash_type`, `code_hash` and `args` are just three fields to configure the lock script for the new mined cell. If you are interested in the details, see this [post](https://github.com/nervosnetwork/rfcs/blob/transaction-structure/rfcs/0021-transaction-structure/0021-transaction-structure.md).

**Comment by doitian** [comment]
The site docs.nervos.org usually only catches up the latest release with even minor version. At the time of writing, the docs are for v0.18.0.

**Comment by qiluge** [comment]
And another question, where is the coinbase tx in block? And are there any difference between coinbase tx and normal tx? Can you show me some example about coinbase structure? Thanks!
