### ISSUE TITLE
Windows node will not synchronize

### ISSUE THREAD

**Issue by ButteryGuitars** [nervosnetwork/ckb#1676]
**Environment**

- **CKB version**: ckb 0.22.0-pre (rylai-v10 f7f5d73c 2019-10-03)
- **Chain**: testnet
- **Operating system**: Windows
- **Arch**: x64
- **Installation**: GitHub Release
**Describe the bug**

The node will start but doesn't seem to want to connect to any peers. I ran a network capture and see it bootstrapping but when I run a get_peers the list is empty.

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

**Comment by driftluo** [comment]
This is not a bug. The currently running test network is 0.21.x, which is not compatible with 0.22.x, which is expected behavior.

**Comment by ButteryGuitars** [comment]
That's extremely helpful and I assume explains why 20.0.0 client won't synchronize either.

I'd love to play around with the full node software but it looks like the assets have all been pulled for 0.21.1 and 0.21.2...

**Comment by ButteryGuitars** [comment]
I tried v0.21.0-rc1 and that won't synchronize either. Still no peers. Are there any ports that need to be open beside 8111 and 8115?

**Comment by driftluo** [comment]
Why don't use 0.21.2？？？？

**Comment by ButteryGuitars** [comment]
Unfortunately the Windows binaries for 0.21.2 appear to have been removed :-(

Maybe it's issue with peer discovery? I've tried Singapore and Ohio as well. I was connected to a peer for a short moment then they were gone. Here is the output when that happend.

.\ckb-cli.exe rpc get_peers
- ←[34mversion←[0m: ←[32munknown←[0m
  ←[34mnode_id←[0m: ←[32mQmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb←[0m
  ←[34maddresses←[0m:
    - ←[34maddress←[0m: ←[32m/ip4/18.136.60.221/tcp/8111←[0m
      ←[34mscore←[0m: ←[32m0x1←[0m

**Comment by ButteryGuitars** [comment]
I understand now what you mean that the genesis block is different and that's why they won't communicate. I keep connected to peers momentarily and that must be why they drop so quickly.

Is there any hope that 0.21.2 Windows binaries will be re-posted?

**Comment by driftluo** [comment]
The test network will switch to 0.22.0 tomorrow, in other words, the current version has a lifespan of less than a day, that means will not release a binary version of the windows again.

0.22.0 will also be released tomorrow

**Comment by ButteryGuitars** [comment]
That's very helpful! I will wait. Thank you for taking the time to answer my questions. It is very much appreciated. I will test the 0.22.0 release tomorrow and report if any issues.

**Comment by ButteryGuitars** [comment]
Confirmed latest 0.22.0 release syncs on windows. Thanks for all the help
