### ISSUE TITLE
Blocks stop downloading, message about banned peers

### ISSUE THREAD

**Issue by ButteryGuitars** [nervosnetwork/ckb#1796]
I've been following along with all the testnet releasess since v0.21.0 and synchronizing blocks has been very dependable and stable. Since v0.24.0 though I'm getting a lot of message about banned peers, invalid blocks and I fall behind the latest block.

I'm running latest ckb full node v0.24.0 on Windows. 

←[1;30m2019-11-06 16:29:38.357 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmYWiwxHasuyou5ztw5uQkHbhm6gs6RB84sbgYxZNGHgaW
) for 300 seconds, reason: relay message process error: HeaderInvalid
←[1;30m2019-11-06 16:29:38.360 -06:00←[0m ←[1;34mNetworkRuntime-7←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(6)
←[1;30m2019-11-06 16:29:38.363 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmamthXehyAgMTKoMVixPgKVSNnswgURKQEJMy28LooxQc
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.363 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(6)
←[1;30m2019-11-06 16:29:38.364 -06:00←[0m ←[1;34mNetworkRuntime-10←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(5)
←[1;30m2019-11-06 16:29:38.369 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmSJTsMsMGBjzv1oBNwQU36VhQRxc2WQpFoRu1ZifYKrjZ
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.369 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(5)
←[1;30m2019-11-06 16:29:38.369 -06:00←[0m ←[1;34mNetworkRuntime-6←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(1)
←[1;30m2019-11-06 16:29:38.374 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmQqYVVigwiogARK4UgB5scgEd9tUfhSiZkLK7bM82cVCu
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.374 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(1)
←[1;30m2019-11-06 16:29:38.375 -06:00←[0m ←[1;34mNetworkRuntime-4←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(7)
←[1;30m2019-11-06 16:29:38.380 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmdP6NA2i9n2Jw2rxYyrEhG7BQZd2KMT6XTJqwVvsK4gh1
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.380 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(7)
←[1;30m2019-11-06 16:29:38.380 -06:00←[0m ←[1;34mNetworkRuntime-10←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(2)
←[1;30m2019-11-06 16:29:38.385 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmUtb5xNNe3vYQng2EY7T6AGSNgah9PDDGuReqxZfeXnHt
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.386 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(2)
←[1;30m2019-11-06 16:29:38.386 -06:00←[0m ←[1;34mNetworkRuntime-1←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(3)
←[1;30m2019-11-06 16:29:38.386 -06:00←[0m ←[1;34mNetworkRuntime-4←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(3)
←[1;30m2019-11-06 16:29:38.392 -06:00←[0m ←[1;34mNetworkRuntime-6←[0m INFO ckb-network  Ban peer PeerId(QmXFU9SfFPHDPWz4pT4ka9PAHkXAsmJxcNCtpddZgpcR6L
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.393 -06:00←[0m ←[1;34mNetworkRuntime-7←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(8)
←[1;30m2019-11-06 16:29:38.393 -06:00←[0m ←[1;34mNetworkRuntime-6←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(8)
←[1;30m2019-11-06 16:29:38.400 -06:00←[0m ←[1;34mNetworkRuntime-5←[0m INFO ckb-network  Ban peer PeerId(QmQF3m14N4qzzsSQK8LwzL2T2NGWtK6aktAKnBHYvT7cit
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:38.400 -06:00←[0m ←[1;34mNetworkRuntime-6←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(4)
←[1;30m2019-11-06 16:29:38.400 -06:00←[0m ←[1;34mNetworkRuntime-1←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(4)
←[1;30m2019-11-06 16:29:46.486 -06:00←[0m ←[1;34mNetworkRuntime-0←[0m INFO ckb-sync  SyncProtocol.connected peer=SessionId(10)
←[1;30m2019-11-06 16:29:46.486 -06:00←[0m ←[1;34mNetworkRuntime-4←[0m INFO ckb-relay  RelayProtocol(1).connected peer=SessionId(10)
←[1;30m2019-11-06 16:29:46.922 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22224, hash: 0xf2d91dad258e5d567bc2b2e6e4cc88ec28ac8400419559
7a3cd9845780c5304d, epoch: 36(15/480), total_diff: 0x110663d2c1a857099, txs: 1
←[1;30m2019-11-06 16:29:47.131 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22225, hash: 0x9dcdbf7fca9b874e08099aa978957eafa16e27a528ccd0
92b8706e0b2cd316c9, epoch: 36(16/480), total_diff: 0x1106c2326d4b81736, txs: 1
←[1;30m2019-11-06 16:29:48.083 -06:00←[0m ←[1;34mNetworkRuntime-1←[0m INFO ckb-relay  RelayProtocol(1).connected peer=SessionId(11)
←[1;30m2019-11-06 16:29:48.083 -06:00←[0m ←[1;34mNetworkRuntime-5←[0m INFO ckb-sync  SyncProtocol.connected peer=SessionId(11)
←[1;30m2019-11-06 16:29:49.147 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22226, hash: 0x970c167913ec88a2215e5bbec14f85b7dcc9d125c0fa07
9c82f1ec51e7a361f0, epoch: 36(17/480), total_diff: 0x1107209218eeabdd3, txs: 1
←[1;30m2019-11-06 16:29:50.296 -06:00←[0m ←[1;34mNetworkRuntime-5←[0m INFO ckb-network  Ban peer PeerId(QmT6DFfm18wtbJz3y4aPNn3ac86N4d4p4xtfQRRPf73frC
) for 300 seconds, reason: relay message process error: HeaderInvalid
←[1;30m2019-11-06 16:29:50.297 -06:00←[0m ←[1;34mNetworkRuntime-9←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(10)
←[1;30m2019-11-06 16:29:50.297 -06:00←[0m ←[1;34mNetworkRuntime-9←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(10)
←[1;30m2019-11-06 16:29:50.320 -06:00←[0m ←[1;34mNetworkRuntime-4←[0m INFO ckb-network  Ban peer PeerId(QmTt6HeNakL8Fpmevrhdna7J4NzEMf9pLchf1CXtmtSrwb
) for 300 seconds, reason: relay message process error: BlockInvalid
←[1;30m2019-11-06 16:29:50.320 -06:00←[0m ←[1;34mNetworkRuntime-5←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(11)
←[1;30m2019-11-06 16:29:50.320 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(11)
←[1;30m2019-11-06 16:30:36.315 -06:00←[0m ←[1;34mNetworkRuntime-4←[0m INFO ckb-relay  RelayProtocol(1).connected peer=SessionId(12)
←[1;30m2019-11-06 16:30:36.315 -06:00←[0m ←[1;34mNetworkRuntime-9←[0m INFO ckb-sync  SyncProtocol.connected peer=SessionId(12)
←[1;30m2019-11-06 16:30:37.199 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22227, hash: 0x5273d2e8bd15738aa5170684ac7a56e0b333afcae7461b
9fb8a85c13086a711c, epoch: 36(18/480), total_diff: 0x11077ef1c491d6470, txs: 1
←[1;30m2019-11-06 16:31:44.173 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22228, hash: 0x4ec7bd02e4ab234a46c9e8e508fb342a8348dd1306a1f3
ccc67b6e8807df4a3f, epoch: 36(19/480), total_diff: 0x1107dd51703500b0d, txs: 1
←[1;30m2019-11-06 16:31:49.524 -06:00←[0m ←[1;34mChainService←[0m INFO ckb-chain  block: 22229, hash: 0x21435fc621505765723e8fe8a04db9f2b5b0d852824a7b
484f9e9156d7f7671b, epoch: 36(20/480), total_diff: 0x11083bb11bd82b1aa, txs: 1
←[1;30m2019-11-06 16:31:53.845 -06:00←[0m ←[1;34mNetworkRuntime-2←[0m INFO ckb-network  Ban peer PeerId(QmY813HR46XPxh6aG6jZZU9VZRuboVBw7Q17n3MnXsts4S
) for 300 seconds, reason: relay message process error: HeaderInvalid
←[1;30m2019-11-06 16:31:53.845 -06:00←[0m ←[1;34mNetworkRuntime-5←[0m INFO ckb-relay  RelayProtocol.disconnected peer=SessionId(12)
←[1;30m2019-11-06 16:31:53.845 -06:00←[0m ←[1;34mNetworkRuntime-6←[0m INFO ckb-sync  SyncProtocol.disconnected peer=SessionId(12)

**Comment by ButteryGuitars** [comment]
if I stop and restart the node, it will download the latest blocks and then stop again. The behavior ends up being that Neuron can't transact when blocks aren't synchronizing.

**Comment by quake** [comment]
Could you edit the configuration file `ckb.toml` and change this line?

```
filter = "info"
``` 
to 

```
filter = "info,sync=debug,relay=debug"
```

Please restart the node after editing, let's see how it goes with more log information.

**Comment by ButteryGuitars** [comment]
Thanks will try and report back. Node stopped sychronizing overnight again as well

**Comment by ButteryGuitars** [comment]
[run.log](https://github.com/nervosnetwork/ckb/files/3820609/run.log)

Unfortunately not a lot of helpful information in the log still. It falls behind on blocks pretty quick though. I've tried blowing away data directory and it comes up to latest block pretty quick then starts lagging until it seems there is no hope of catching up. Stopping and starting node always brings it back into sync for a short time

**Comment by driftluo** [comment]
I tried it on my win10 virtual machine and everything is normal. Can't reproduce your problem

win version: 10.0.17134.1069
ckb version: https://github.com/nervosnetwork/ckb/releases/download/v0.24.0/ckb_v0.24.0_x86_64-pc-windows-msvc.zip

I am more skeptical about whether it is a problem with your version.
