### ISSUE TITLE
How to get a block header (for pow) from template

### ISSUE THREAD

**Issue by maoxs2** [nervosnetwork/ckb#1798]
It seems that the block template is converted into packed block and then fetch the header from it, but the molecule serialization process is confusing. So, is there any simple way bypassing the packing block get the header directly? 

What's more, it would be great that add the blocktemplate and related methods to https://github.com/nervosnetwork/ckb-types-go. If you answered, I would take a try on this.

**Comment by driftluo** [comment]
There is no way to bypass the molecule.

The molecule is to ensure that the results are platform-independent, language-independent, and the results are consistent across any implementation.

**Comment by maoxs2** [comment]
The meaning is, for reaching that, I have to write a "go-molecule" implement first by myself?

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/ckb-types-go this repo simply implements the serialization method of the type currently needed. Or, you can use the ffi version

**Comment by maoxs2** [comment]
thanks
