### ISSUE TITLE
MacOS release compiled for 10.15+ only?

### ISSUE THREAD

**Issue by pstarSR** [nervosnetwork/ckb#1827]
Mac OS High Sierra -  seems pre-compiled release for Darwin is set for 10.15+ only.

- **CKB version**: output of `ckb --version`
- **Chain**: mainnet ...
- **Operating system**: macOS 10.13
- **Arch**: x64
- **Installation**: GitHub Release 25.1

trying to run the node, to get started with the wallet etc. Command line drops an error
( ckb init --mainnet )
" /Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb init --mainnet
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6"

( ckb run command )
"/Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb run
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Cryptoprojects/ckb_v0.25.1_x86_64-apple-darwin/ckb (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6"

**Comment by doitian** [comment]
Thanks for the reporting. This package is built in my laptop locally to avoid the runtime dependency openssl. I'll publish a new one via CI instead, which should resolve your issue.

**Comment by doitian** [comment]
A new package uploaded, could you help to verify whether it works in old macOS versions?

The new package checksum is:

```
310a2cd113d9866337c6ce187ad36db7db7e964025bce8c1e8ed82cc805986d2  ckb_v0.25.1_x86_64-apple-darwin.zip
```

which can be downloaded [here](https://github.com/nervosnetwork/ckb/releases/download/v0.25.1/ckb_v0.25.1_x86_64-apple-darwin.zip)

**Comment by pstarSR** [comment]
ill check it now
