### ISSUE TITLE
Running ckb 0.25.2 (dda4ed9 2019-11-17) 

### ISSUE THREAD

**Issue by Rbchi** [nervosnetwork/ckb#1831]
Is the same way to run node between 25.1 and 25.2?

To start lina using v0.25.1 binaries:
```
ckb init --chain mainnet
ckb run
```

I met this problem
```
MacBook-Air:ckb_v0.25.2_x86_64-apple-darwin XXX$ ./ckb --version
ckb 0.25.2 (dda4ed9 2019-11-17)
MacBook-Air:ckb_v0.25.2_x86_64-apple-darwin XXX$ ./ckb-cli --version
ckb-cli 0.25.2 (6ca7bbb 2019-11-17)
MacBook-Air:ckb_v0.25.2_x86_64-apple-darwin XXX$ ckb init --chain mainnet
-bash: cab: command not found
```

**Comment by driftluo** [comment]
So why use `./ckb` on first two command and the last use `ckb`?

**Comment by doitian** [comment]
Most of our examples assume that the shell can find the executable ckb. If you don't know how to copy the ckb executable to a directory in the PATH environment variable or how add a directory in to the PATH environment, please always cd into the directory and use `./ckb` and `./ckb-cli` to run the command.

**Comment by Rbchi** [comment]
Sorry I am fucking dumb and your time.
