### ISSUE TITLE
win10 failed

### ISSUE THREAD

**Issue by lixinyuan1213** [nervosnetwork/ckb#1884]
**Environment**

- **CKB version**: output of `ckb --version`
- **Chain**: dev / staging / testnet / mainnet ...
- **Operating system**: Linux / macOS / Windows
- **Arch**: x64
- **Installation**: GitHub Release / Built from source

**Describe the bug**

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

win10: vc++2015 errors as follows:

Caused by:
  process didn't exit successfully: `F:\ckb1\ckb-develop\target\debug\build\ckb-vm-5cf14b38f7ae956a\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Error running command: "clang" "-E" "src/machine/asm/execute.S" "-o" "F:\\ckb1\\ckb-develop\\target\\debug\\build\\ckb-vm-52376d7541b855f2\\out\\execute-expanded.S" error: Os { code: 2, kind: NotFound, message: "系统找不到指定的文件。" }', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\ckb-vm-0.18.1\build.rs:26:17
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:47
   2: std::sys_common::backtrace::print
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\sys_common\backtrace.rs:36
   3: std::panicking::default_hook::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:200
   4: std::panicking::default_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:214
   5: std::panicking::rust_panic_with_hook
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:477
   6: std::panicking::continue_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:384
   7: std::panicking::begin_panic_fmt
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:339
   8: build_script_build::main::run_command::{{closure}}
             at .\build.rs:26
   9: core::result::Result<std::process::ExitStatus, std::io::error::Error>::unwrap_or_else<std::process::ExitStatus,std::io::error::Error,closure-0>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libcore\result.rs:818
  10: build_script_build::main::run_command
             at .\build.rs:25
  11: build_script_build::main
             at .\build.rs:47
  12: std::rt::lang_start::{{closure}}<()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  13: std::rt::lang_start_internal::{{closure}}
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:49
  14: std::panicking::try::do_call<closure-0,i32>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:296
  15: panic_unwind::__rust_maybe_catch_panic
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libpanic_unwind\lib.rs:80
  16: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panicking.rs:275
  17: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\panic.rs:394
  18: std::rt::lang_start_internal
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\/src\libstd\rt.rs:48
  19: std::rt::lang_start<()>
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\libstd\rt.rs:64
  20: main
  21: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  22: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  23: BaseThreadInitThunk
  24: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by xxuejie** [comment]
To build CKB on Windows, please install [LLVM](http://releases.llvm.org/download.html) as well as [yasm](https://yasm.tortall.net/), those are required build dependencies in addition to Visual Studio

**Comment by driftluo** [comment]
you can follow the ci test to build ckb on Windows:
https://github.com/nervosnetwork/ckb/blob/develop/devtools/azure/windows-dependencies.yml
https://github.com/nervosnetwork/ckb/blob/develop/azure-pipelines.yml

**Comment by lixinyuan1213** [comment]
> To build CKB on Windows, please install [LLVM](http://releases.llvm.org/download.html) as well as [yasm](https://yasm.tortall.net/), those are required build dependencies in addition to Visual Studio

thank you

**Comment by lixinyuan1213** [comment]
> you can follow the ci test to build ckb on Windows:
> https://github.com/nervosnetwork/ckb/blob/develop/devtools/azure/windows-dependencies.yml
> https://github.com/nervosnetwork/ckb/blob/develop/azure-pipelines.yml

thank you

**Comment by lixinyuan1213** [comment]
Now that the problem is solved
