### ISSUE TITLE
Compiling jemalloc-sys v0.3.0 error: failed to run custom build command for `jemalloc-sys v0.3.0`

### ISSUE THREAD

**Issue by lixinyuan1213** [nervosnetwork/ckb#1886]
ubuntu18 arm x64:

RUSTFLAGS="--cfg disable_faketime" cargo build  --release
   Compiling jemalloc-sys v0.3.0
error: failed to run custom build command for `jemalloc-sys v0.3.0`

Caused by:
  process didn't exit successfully: `/share_files/ckb/target/release/build/jemalloc-sys-647a71de462ac59b/build-script-build` (exit code: 101)
--- stdout
TARGET=x86_64-unknown-linux-gnu
HOST=x86_64-unknown-linux-gnu
NUM_JOBS=1
OUT_DIR="/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out"
BUILD_DIR="/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out/build"
SRC_DIR="/root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.0"
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
CC="cc"
CFLAGS="-O3 -ffunction-sections -fdata-sections -fPIC -m64 -Wall"
JEMALLOC_SRC_DIR="/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out/jemalloc"
cargo:rustc-cfg=prefixed
--with-jemalloc-prefix=_rjem_
running: "sh" "/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out"
checking for xsltproc... false
checking for x86_64-unknown-linux-gnu-gcc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling...
--- stderr
configure: error: in `/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out/build':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
thread 'main' panicked at 'command did not execute successfully: "sh" "/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/share_files/ckb/target/release/build/jemalloc-sys-7672a71a57e64288/out"
expected success, got: exit code: 1', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/jemalloc-sys-0.3.0/build.rs:370:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Makefile:82: recipe for target 'prod' failed
make: *** [prod] Error 101

**Comment by xxuejie** [comment]
It seems your machine fails to build jemalloc, can you search for `config.log` in `target` to see what went wrong with jemalloc? My guess is that there's missing dependencies required by jemalloc.

**Comment by lixinyuan1213** [comment]
> It seems your machine fails to build jemalloc, can you search for `config.log` in `target` to see what went wrong with jemalloc? My guess is that there's missing dependencies required by jemalloc.

thank you
