### ISSUE TITLE
windows failed to run custom build command for `ckb-vm v0.18.1`

### ISSUE THREAD

**Issue by xingchenzi** [nervosnetwork/ckb#1887]
yasm: FATAL: unrecognized parser `gnu'
thread 'main' panicked at 'Command "yasm" "-p" "gnu" "-f" "x64" "-m" "amd64"

**Comment by driftluo** [comment]
see https://github.com/nervosnetwork/ckb-vm/pull/94 and https://github.com/nervosnetwork/ckb/pull/1885，yasm upgrade and use `gas` instead of `gnu`
