### ISSUE TITLE
can ckb show more error messages

### ISSUE THREAD

**Issue by shaojunda** [nervosnetwork/ckb#1964]
when I make a UDT transfer I got an error:
 `CKB::RPCError: jsonrpc error: {:code=>-3, :message=>"Script: InvalidCodeHash"}`

just looking at this error, I don't know what went wrong, can we show more error messages to help debug?

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/ckb/blob/develop/script/src/error.rs 

`InvalidCodeHash` means some script hash can't find on chain

**Comment by shaojunda** [comment]
> [/script/src/error.rs@`develop`](https://github.com/nervosnetwork/ckb/blob/develop/script/src/error.rs) [](/nervosnetwork/ckb/blob/HEAD@{2020-03-11T09:24:38Z}/script/src/error.rs)
> 
> `InvalidCodeHash` means some script hash can't find on the resource, may be missing the dep cell/input cell

thanks, in the end, I located the problem, but I also hope that the error message can be more detailed.
