### ISSUE TITLE
Suggest to add a new RPC for known net tip block number

### ISSUE THREAD

**Issue by CipherWang** [nervosnetwork/ckb#2122]
Current RPC related to tip block number is `get_tip_block_number`. It returns the latest block number synced by current node. But in some circumstance, application needs to know the latest block number of the network to estimate the sync percentage and how much time to fully synchronized. Of cause it's not a accurate result, but still provides valuable information to users.

**Comment by doitian** [comment]
Closed by https://github.com/nervosnetwork/ckb/pull/2188
