### ISSUE TITLE
RPC doc for trace_transaction and get_transaction_trace is misleading

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb#217]
**Describe the bug**
RPC doc for `trace_transaction` and `get_transaction_trace` is misleading.

**To Reproduce**
1. Go to https://github.com/nervosnetwork/ckb/blob/e759128af3b041406a6204369ea273b266ce12a7/rpc/doc.md#trace_transaction
2. Check the method description
3. Both methods describe themselves as `Creates new transaction`.

**Expected behavior**
Proper description of these two RPC methods.

**Comment by doitian** [comment]
The RPC `get_transaction_trace` gets the status of the transaction submited by `trace_transaction`.

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/218
