### ISSUE TITLE
get_cells

### ISSUE THREAD

**Issue by lishuailibertine** [nervosnetwork/ckb#2205]
Can the 'get_cells' RPC method be added to the node? When I initiate the transfer, because the balance of the current account is not enough, I will use another account as' out cell '. In this case, 'get_cells_by_lock_hash' is not very good!!

**Comment by doitian** [comment]
`get_cells` by what?

**Comment by lishuailibertine** [comment]
@doitian  I mean there is no RPC interface that can pull the balance of all my extended accounts and my change account, but of course it can be called 'get_cells_all_account' similarly.

**Comment by doitian** [comment]
It is recommended to use cell index service such as https://github.com/quake/ckb-indexer , all the indexing RPCs built in the CKB will be deprecated soon.
