### ISSUE TITLE
RPC `get_cells_by_lock_hash`接口问题

### ISSUE THREAD

**Issue by apple94586** [nervosnetwork/ckb#2211]
我有一个账户，收款地址第20个才有余额，我用这个`get_cells_by_lock_hash`接口去获取总余额的时候,假如现在的块高度为100万，就需要请求这个接口1万次，20个地址需要20万次；有其他办法比较方面的获取总余额吗?

**Comment by CipherWang** [comment]
建议用 ckb-indexer 简化请求: https://github.com/quake/ckb-indexer
它会索引所有的地址余额（需要20~40min首次索引时间）

**Comment by apple94586** [comment]
@CipherWang 如果是自己的节点， 这个是需要部署到节点上的吗？我可以用官方的节点吗？希望可以在rpc文档中补充一下。

**Comment by doitian** [comment]
It is recommended to use cell index service such as https://github.com/quake/ckb-indexer , all the indexing RPCs built in the CKB will be deprecated soon.

推荐使用外部服务来索引 cells，比如 https://github.com/quake/ckb-indexer 。CKB 内置的索引 RPCs 都不再推荐使用并会在近期标记为 Deprecated.

ckb-indexer 需要单独部署并需要和 ckb 节点同时运行。CKB Network 是去中心的环境，没有所谓“官方”的概念，Foundation 不会提供类似的中心化服务。
