### ISSUE TITLE
estimate_fee_rate

### ISSUE THREAD

**Issue by lishuailibertine** [nervosnetwork/ckb#2218]
RPC Error

{
    "jsonrpc": "2.0",
    "error": {
        "code": -3,
        "message": "estimate_fee_rate have been deprecated due to it has availability and performance issue"
    },
    "id": 2
}

**Comment by driftluo** [comment]
https://github.com/nervosnetwork/ckb/pull/2126

**Comment by lishuailibertine** [comment]
@driftluo  How do I calculate the miner's fee

**Comment by doitian** [comment]
Since the memory pool is nearly empty currently, setting the minimal fee is sufficient:

```
min fee = tx size in bytes * 1_000_000 shannons/bytes
```

We'll add a new RPC to return the median fee rate in recent blocks soon and a new estimator later as an extension app.
