### ISSUE TITLE
The response data is too large

### ISSUE THREAD

**Issue by lishuailibertine** [nervosnetwork/ckb#2230]
![截屏2020-08-14 下午2 01 39](https://user-images.githubusercontent.com/7145192/90218863-68bce980-de37-11ea-93fc-83003440298f.png)

There are alternative interfaces to get the data？

**Comment by doitian** [comment]
Do you have any suggestion?

**Comment by lishuailibertine** [comment]
Because this interface is used on the phone, such a large response data will cause a long request time, to the user experience is not good!

![截屏2020-08-17 上午9 59 31](https://user-images.githubusercontent.com/7145192/90351001-6f36a580-e071-11ea-9ac3-c4abef5adc80.png)

Does the field 'SystemScript' change often? I use this interface to get this object. Having to request this interface every time a transaction request is made can be a significant performance penalty.

**Comment by quake** [comment]
you may cache the genesis block in client side since it's immutable instead of query it via rpc each time.

**Comment by lishuailibertine** [comment]
Ok, thank  your suggestion
