### ISSUE TITLE
Run error: GenesisMismatch

### ISSUE THREAD

**Issue by JiashengRen** [nervosnetwork/ckb#2254]
version : 0.34.2
I input the command : ckb run 
it shows me : 
`Run error: Error { kind: GenesisMismatch { expected:Byte32(xxx...),actual: Byte32(yyy...)}`
please help me!!
Thanks!!

**Comment by driftluo** [comment]
ckb will load `ckb.toml` to decide which net will be started，and then check the chain data before start.

`GenesisMismatch` indicates that your configuration file(`ckb.toml`) does not match the data information, please check

**Comment by doitian** [comment]
Actual is your chain genesis hash stored in database. Expected is your chain genesis hash configured in config file. You can either update your config file to match your database, or clean the database and re-sync from the network.

**Comment by JiashengRen** [comment]
Thanks very much
