### ISSUE TITLE
Improve the experience to build and run ckb

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#2256]
https://talk.nervos.org/t/experience-report-first-time-building-and-running-ckb/4518

* [ ] Just let users to build using `cargo build` or `cargo build --release`. The crate faketime is designed that it has little overhead when it is not used, so don't bother developers with it.
* [ ] Add a VERSIONS file to trace of the the corresponding ckb-cli, ckb-bench versions.
* [ ] Print genesis and spec hash in `ckb init`
* [ ] ckb-cli should prints a warning in debug build that some commands are extremely slow.
* [ ] Improve the comment for block assembler
    * Simplify the comment to explain how to setup a simple secp256k1 lock in testnet/mainnet.
    * Use a public-known key pair in dev chain.
    * Write an essay to explain the advantage usage of block assembler.

---

https://github.com/nervosnetwork/ckb/issues/2256#issuecomment-757563287

* [ ] Apple M1 support

**Comment by zhangsoledad** [comment]
- [ ] Apple M1 support
