### ISSUE TITLE
When block verifier collects proposal ids, it does not skip `transaction_propagation_time` blocks

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#226]
https://github.com/nervosnetwork/ckb/blob/fcc01da8a4774cae7245d13143f1d77c5e05efee/verification/src/block_verifier.rs#L517

**Comment by doitian** [comment]
@zhangsoledad please confirm and close this issue

**Comment by zhangsoledad** [comment]
Closed by https://github.com/nervosnetwork/ckb/pull/291
