### ISSUE TITLE
[docs] the cli type_hash returns "No config file found!"

### ISSUE THREAD

**Issue by kellyshang** [nervosnetwork/ckb#227]
in CKB's repo directory, use the command "./target/release/ckb cli type_hash" now returns "No config file found!".

**Comment by doitian** [comment]
When a subcommand needs a config file, it tries `ckb.json`, `nodes/default.json` in working directory when no one is specified in command line.

**Comment by kellyshang** [comment]
I tried in v0.6.0 start from removing old `nodes` folder and copying the `node_template`, it can return the type_hash now. 
Thanks for all your reply.
