### ISSUE TITLE
Second send transaction issue

### ISSUE THREAD

**Issue by AnasSaeed123** [nervosnetwork/ckb#2306]
After receiving coins from faucet, I have done my 1st transaction using tx hash given by faucet by placing it in previousoutput section in json-rpc. But when I am doing second transaction from same address using tx hash of 1st transaction by putting it in previousoutput section in json-rpc it gives me this error:

"message": "CKBInternalError: Script(TransactionScriptError { source: Inputs[0].Lock, cause: ValidationFailure(-31): the exit code is per script specific, for system scripts, please check https://github.com/nervosnetwork/ckb-system-scripts/wiki/Error-codes })"

**Comment by AnasSaeed123** [comment]
Json-rpc:

send_transaction
https://github.com/nervosnetwork/ckb/blob/master/rpc/README.md#send_transaction

**Comment by driftluo** [comment]
your signature is invalid，-31 Error code is means

> The public key hash calculated from the signature does not match public key hash requested in the script. Note due to the way recoverable signature works, an invalid signature can actual signal this error.

**Comment by AnasSaeed123** [comment]
> your signature is invalid，-31 Error code is means
> 
> > The public key hash calculated from the signature does not match public key hash requested in the script. Note due to the way recoverable signature works, an invalid signature can actual signal this error.
