### ISSUE TITLE
Blocks Downloading 

### ISSUE THREAD

**Issue by DanishBawany** [nervosnetwork/ckb#2564]
**Environment**
i'm using Ubuntu 20.04 on Dell 5559
CPU: Intel Core i5-6200U Dual-Core
GPU: Intel HD Graphics 520
Graphics Processor: AMD Radeon R5 M335
RAM: 8GB DDR3, 1600 MHz

- **CKB version**: output of `ckb 0.39.2 (2d56a24 2021-01-30)`
- **Chain**: testnet  ...
- **Operating system**: Linux 
- **Ubuntu**: 20.04
- **Installation**: GitHub Release / Built from source

**Describe the bug**

_Blocks downloading taking too long before it downloaded around 1m block in a hour or so, Now it takes avg. 30 sec per block to download after reaching download to 1m+.._

**Comment by quake** [comment]
https://t.me/nervos_ckb_dev/8385

Bawani, [Feb 12, 2021 at 6:15:22 PM]:
after reaching 1m+ blocks its been downloading from 12 hours and yet reach only 1,164,372, any idea how long it will take?

Quake Wang, [Feb 12, 2021 at 6:16:13 PM]:
current testnet tip is 1,164,380, I think you have synced with testnet already

please checkout: https://explorer.nervos.org/aggron/

Bawani, [Feb 12, 2021 at 6:18:33 PM]:
you are right, it looks like.
