### ISSUE TITLE
"Illegal instruction (core dumped)" when trying to run ckb from linux terminal

### ISSUE THREAD

**Issue by ItalianNoob** [nervosnetwork/ckb#2623]
**Environment**

- **CKB version**: none
- **Chain**: none
- **Operating system**: Linux 
- **Arch**: x64
- **Installation**: GitHub Release 

**Describe the bug**

I tried to install ckb from the release file on github version 0.40 but whenever I try to run it I get the "illegal instruction (core dumped) error.

**Comment by driftluo** [comment]
Illegal instruction means that the CPU of your machine does not support some common instructions of modern CPU, such as `+aes,+pclmul,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2`

Of course, the GitHub release version is not very radically optimized. It only uses the part of the machine support provided by Travis. In theory, it should only be `aes,sse` 

If you really want to run ckb on this machine, it is recommended to compile ckb binary from the source code on this machine, and then use.

Before compiling, you most likely need to install some development environments, there may be:
```
$ apt install libssl-dev pkg-config autoconf libtool git
```
then:
```
$ git clone https://github.com/nervosnetwork/ckb.git
$ cd ckb
$ make prod
```
