### ISSUE TITLE
 client ERROR ckb_miner::client  rpc call get_block_template error

### ISSUE THREAD

**Issue by xiaobanni** [nervosnetwork/ckb#2731]
Thanks for this project, I am a supporter of CKB.

I want to execute the command `ckb miner`, but encountered an unsolvable error.

The process is mainly based on `https://github.com/nervosnetwork/ckb/blob/master/docs/quick-start.md` and `https://docs.nervos.org/docs/basics/guides/devchain` as follow in **windows10**.

1. download `ckb_v0.41.0_x86_64-pc-windows-msvc` from [ckb 0.41.0 (d3a609a 2021-04-22)](https://github.com/nervosnetwork/ckb/releases/tag/v0.41.0)
2. double click `ckb-init-mainnet.bat` to initialize a mainnet node directory.
3. run `ckb-cli account new`  to get a new account and modify the `args` and `message` parameters in the ckb.toml file to my lock_arg value and "0x"
4. double click `ckb-run.bat` to start the node and wait until get the highest block
5. run `ckb miner` in a separate terminal but find an error:
**client ERROR ckb_miner::client  rpc call get_block_template error: Fail(Error { code: ServerError(-4), message: "RPCModuleIsDisabled: This RPC method is in the module `Miner`. Please modify `rpc.modules` and `block_assembler` in ckb.toml and restart the ckb node to enable it.", data: None })**

I want to know how to solve this error, I look forward to your answer, thank you.

**Comment by driftluo** [comment]
Have you removed these leading "#" matches, these "#" indicate that the current line is a comment, does not take effect 
```toml
# [block_assembler]
# code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
# args = "ckb cli blake160 <compressed-pubkey>"
# hash_type = "type"
# message = "A 0x-prefixed hex string"
```

**Comment by xiaobanni** [comment]
Thanks very much.
So if I want to mine, I must purchase a dedicated mining machine or join a mining pool, right?

**Comment by driftluo** [comment]
> So if I want to mine, I must purchase a dedicated mining machine or join a mining pool, right?

So far, yes

**Comment by xiaobanni** [comment]
Understood, thank you again for your help.
And if it is convenient, can you recommend a CKB mining pool?

**Comment by driftluo** [comment]
> And if it is convenient, can you recommend a CKB mining pool?

Maybe you can find relevant information from [here](https://t.me/nervos_mining), I don’t know much about it

**Comment by xiaobanni** [comment]
All my questions have been answered so far, thanks.

**Comment by xiaobanni** [comment]
> By the way, judging from the current computing power of the main net, it is impossible to use CPU miner to get new blocks.

One more question, **impossible** here refers to theoretically impossible or too small to be ignored. That is, if lucky enough, is it possible to get a block?

**Comment by driftluo** [comment]
> One more question, impossible here refers to theoretically impossible or too small to be ignored. That is, if lucky enough, is it possible to get a block?

Hope you have such luck. . . although I think it's close to zero
