### ISSUE TITLE
Documentation: List well known lock scripts and describe process to disable functionality of well_known_scripts_only,

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb#3056]
#### Is your feature request related to a problem? Please describe.
There is not enough information about the new default functionality for well_known_scripts_only for developers to upgrade properly.

#### Describe the solution you'd like
Within the [documentation](https://github.com/nervosnetwork/ckb/wiki/Transaction-%C2%BB-Default-Outputs-Validator), it would be helpful if the well-known lock scripts were listed for the Testnet and Mainnet. It would also be highly beneficial to describe how to disable this functionality since this is a breaking change.

**Comment by quake** [comment]
wiki has been updated, thanks for your report.

**Comment by doitian** [comment]
`well_known_scripts_only` has been disabled by default.
