### ISSUE TITLE
Remove Clippy allow lint

### ISSUE THREAD

**Issue by ZhangHanDong** [nervosnetwork/ckb#3062]
Sorry, this issue should not be a bug, but there is no category in the template that fits this issue.

there is the following code in  the [chain/src/chain.rs#L201](https://github.com/nervosnetwork/ckb/blob/develop/chain/src/chain.rs#L201)

```rust

     // remove `allow` tag when https://github.com/crossbeam-rs/crossbeam/issues/404 is solved
    /// start background single-threaded service with specified thread_name.
    #[allow(clippy::zero_ptr, clippy::drop_copy)]
    pub fn start<S: ToString>(mut self, thread_name: Option<S>) -> ChainController { // ... }
```

 `#[allow( clippy::drop_copy)]` can be removed because the crossbeam issues [#404](https://github.com/crossbeam-rs/crossbeam/issues/404) has now been fixed: [https://github.com/crossbeam-rs/crossbeam/pull/407](https://github.com/crossbeam-rs/crossbeam/pull/407)

**Comment by zhangsoledad** [comment]
Appreciate your reporting.
