### ISSUE TITLE
User reports excessively slow migration in Windows 10 Neuron.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb#3168]
## Bug Report
After assisting a user to start a manual migration, the process was found to be unexpectedly slow. On his computer, the progress was only this far after well over an hour of waiting:

```
[ [00:41:48] [>>--------------------------------------->---------------------------------------] 25044/2664110 (3d)
```

His computer specs are reasonable. It seems like something may not be operating correctly.

處理器    Intel(R) Core(TM) i5-3450 CPU @ 3.10GHz   3.10 GHz
已安裝記憶體(RAM)    8.00 GB
[neuron_debug_1636266207310.zip](https://github.com/nervosnetwork/ckb/files/7491846/neuron_debug_1636266207310.zip)

### Current Behavior
Database migration is taking hours.

### Expected Behavior
On computers where I have done the migration, it usually only took a few minutes, even on a low spec computer.

### Environment

- **CKB version**: [the output of `ckb --version`]
v0.101.0 

- **Chain**: [dev, staging, testnet, mainnet]
mainnet

- **Operating system**: [Ubuntu 20.04, macOS 11.4, Windows 10]
Windows 10

- **Arch**: x64 [the output of `uname -a`]
x64

- **Installation**: [GitHub Release, Built from source]
Neuron v0.101.0

**Comment by driftluo** [comment]
From your description, your data migration is the 0.43 data migration, which is a very fast one, and the 40-minute data migration you reported is not the same as the 0.43 migration

There are multiple data migration processes from 0.25 to 0.100. It is necessary to load the full amount of data from the database many times, and then write it again. As the amount of data increases, the processing time also increases linearly. Data migration does not consume much CPU and memory. The biggest bottleneck lies in disk io
