### ISSUE TITLE
Segwit fix CKB malleability

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#330]
## BIPs
* [bip-0141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki) The main definition of Segregated Witness.
* [bip-0142](https://github.com/bitcoin/bips/blob/master/bip-0142.mediawiki) Address Format for Segregated Witness
* [bip-0143](https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki) Transaction Signature Verification for Version 0 Witness Program
* [bip-0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki) Peer Services—New network messages and serialization formats
* [bip-0145](https://github.com/bitcoin/bips/blob/master/bip-0145.mediawiki) getblocktemplate Updates for Segregated Witness (for mining)

## Notes
* Move out witness from transaction.
* Transaction `txid` is immutable.
* Signature contains input value, safe for offchain transaction creation.

## Why Segwit
* Fixes [transaction malleability](https://en.bitcoin.it/wiki/Transaction_malleability)
* Witness is optional. Saves bandwidth for light nodes.
* Improves signature verification computation time (BIP 143), solves the quadratic signature hashing.
* Increases block capacity.
* It is possible to upgrade lock/unlock script using soft fork

**Comment by zhangsoledad** [comment]
https://github.com/cryptape/ckb-internal/issues/725

**Comment by janx** [comment]
我们也需要通过SegWit解决quadratic hashing的问题，现有的sighash实现(ruby)应该是有这个问题的。

https://bitcoincore.org/en/2016/01/26/segwit-benefits/

**Comment by doitian** [comment]
Bitcoin Segwit 是通过把 tx 架构化成一个类似树状的结构，经常一起 digest 的部分放在一个节点下。在计算签名如果刚好是用到一个节点下的所有数据，就直接用这部分的预先 digest 好的 4 个字节来参与签名的 digest。因为 digest 和输入数据的长度是线性相关的，把经常要 digest 的大段二进制用短的 4 个字节代替能显著降低计算量。举个例子：

假如所有的 outputs 一起有 100 个字节，有 10 个 inputs，然后 10 个 inputs 的验证签名需要 digest 自己和所有的 outputs。如果不考虑每个 input 的大小，那总计要对 100 个字节 digest 10 次，开销事 1000。而如果把 outputs 先做一次 digest 得到 4 个字节，然后每个 input 验签是用这 4 个字节加上 input 来 digest，那么开销就是 digest outputs 1 次的 100 加上 4 个字节计算 10 次，总计 140。

注意到这个优化对于 cell data 同样有意义，对于要对 data 部分反复 digest 的部分替换成先算出 cell data 的 hash，然后用 hash 参与 signature digest，能减少重复计算。
