### ISSUE TITLE
Add a verification rule that the `type` field of a cellbase output cell must be absent

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#331]

**Comment by zhangsoledad** [comment]
Zhang Dingwei, [14.01.19 18:14]
cycles_limit 不包含 cellbase 
或者说 cellbase 的结构需要不要找个地方描述一下

Xuejie Xiao, [14.01.19 18:15]
目前 cycles 没处理 cellbase 是因为： 1. 现在 cellbase 格式有点特殊；2. 一般情况下 cellbase 没有合约

Xuejie Xiao, [14.01.19 18:15]
但是实际上我们现在有个小 bug：共识层是没有限制 cellbase 的 CellOutput 不能有 type 的，那么这个 type 消耗的 cycles 就不会被计算

ian, [14.01.19 19:13]
cellbase 里的 type 可以考虑用来做直接收 UDT 做手续费的功能，让这里的合约能便利所有 tx

ian, [14.01.19 19:15]
/newissue 共识层没有限制 cellbase 的 CellOutput 不能有 type

J jy, [14.01.19 20:10]
那么能不能 cellbase 的cycles也算进去呢？

Xuejie Xiao, [14.01.19 20:10]
可以，所以我说这是个 bug。之前做那个功能时欠考虑了

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/335
