### ISSUE TITLE
Implement `healthcheck` instruction inside ckb docker image

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/ckb#3321]
#### Is your feature request related to a problem? Please describe.
CKB might take some time to launch. Before launching successfully, the RPC service can not accept requests. DApp projects that integrate CKB via docker-compose or other docker management tools must perform a health check on the CKB service before making any CKB requests.

#### Describe the solution you'd like
I think a built-in [`healthcheck`](https://docs.docker.com/engine/reference/builder/#healthcheck) inside the CKB docker image could make docker integration easier.

**Comment by chanhsu001** [comment]
> CKB might take some time to launch.

some time means minutes? or seconds (sorry, not ever run ckb-binary  in docker image)

supposed command line would be:  

```
$ckb state
$ckb is up / ckb is starting (not ready?)
```

**Comment by keroro520** [comment]
> > CKB might take some time to launch.
> 
> some time means minutes? or seconds (sorry, not ever run ckb-binary in docker image)
> 

I am not sure about it. CKB reprocess transactions persisted within `data/tx_pool/`. I guess the launch time is related to the number of transactions within `data/tx_pool/`.
