### ISSUE TITLE
`get_trasaction` rpc needs to be able to support returning raw molecule hex bytes

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb#3424]
## Feature Request

`get_transaction` rpc needs to be able to support returning raw molecule hex bytes

#### Describe the solution you'd like

Previously, we used the verbosity parameter to control the mode of the extended `get_transaction`. verbosity=0 has been marked as deprecated and we can reuse verbosity=0 to indicate that raw hex bytes are returned. This has the advantage of being consistent with the behavior of `get_block` verbosity=0

#### Describe alternatives you've considered

New rpc `get_raw_transaction`.

**Comment by eval-exec** [comment]
The `verbosity=0` has been marked as deprecated, but the test suites still use `verbosity=0`:

https://github.com/eval-exec/ckb/blob/e592a4374ce8d87aaf420d93cd9f6e37b69e6317/test/src/rpc.rs#L71-L78
