### ISSUE TITLE
Nginx API Gateway examples

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3513]
#### Is your feature request related to a problem? Please describe.

As said in the [[CKB RPC document](https://github.com/nervosnetwork/ckb/tree/develop/rpc)](https://github.com/nervosnetwork/ckb/tree/develop/rpc),

> Allowing arbitrary machines to access the JSON-RPC port (using the `rpc.listen_address` configuration option) is dangerous and strongly discouraged. Please strictly limit the access to only trusted machines.

But there's no documents about how to configure the RPC access control.

#### Describe the solution you'd like

This issue asks for example configurations of the API gateway for CKB. Except the popular gateway Nginx, it's also welcome to contribute examples for other gateways such as Caddy.

The recommended scenarios for the examples:

- How to limit access by source IP.
- How to set up simple HTTP basic auth.
- How to limit access by RPC method.
- How to throttle the RPC requests.
- Basic gotchas, for example, the default body size is not enough to submit a fully packaged block.

**Comment by zhangsoledad** [comment]
https://github.com/jiangxianliang007/ckb-nginx-proxy

**Comment by doitian** [comment]
> https://github.com/jiangxianliang007/ckb-nginx-proxy

Migrated to https://github.com/cryptape/ckb-nginx-proxy

**Comment by doitian** [comment]
I added a topic [#ckb-rpc-proxy](https://github.com/topics/ckb-rpc-proxy) to https://github.com/cryptape/ckb-nginx-proxy . Once GitHub has indexed the repository under the topic, we can add the topic link in the RPC doc.
