### ISSUE TITLE
error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yanguoyu** [nervosnetwork/ckb#3560]
### Current Behavior

1. Download [release](https://github.com/nervosnetwork/ckb/releases/download/v0.104.0/ckb_v0.104.0_x86_64-unknown-linux-gnu.tar.gz)
2. tar && cd ckb_v0.104.0_x86_64-unknown-linux-gnu
3. ./ckb init --chain testnet -C testnet
4. Throw error
<img width="931" alt="image" src="https://user-images.githubusercontent.com/12881040/187360624-47e9bcc1-d10a-42c8-84af-63c502de410c.png">
 
### Expected Behavior

It can start success.
### Environment

- **CKB version**: v0.104.0
- **Chain**: testnet
- **Operating system**: Linux Mint 21 Vanessa
- **Arch**: x86_64
- **Installation**: [GitHub Release]

### Additional context/Screenshots

Linux Mint 21 default install openssl 3.0.2. I don't know whether it will help you.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/12881040/187361385-3f851afa-60d6-424e-916f-4f85cf9a2914.png">

<img width="959" alt="image" src="https://user-images.githubusercontent.com/12881040/187361423-f8f947a6-8da8-4134-99ad-f22f12a4cbc5.png">

**Comment by driftluo** [comment]
The runtime environment of ckb depends on libssl1.1.1, you can run `sudo apt-get install libssl1.0.0` to install `libssl1.1.1`.

**Comment by doitian** [comment]
Hi, we choose not to bundle OpenSSL statically so user can upgrade libssl for security. It means the binaries we built cannot cover all environments. There are three ways to work around this:

1. Use the platforms in [tier 1 and 2](https://github.com/nervosnetwork/ckb/blob/develop/docs/platform-support.md)
2. Install the correct libssl version
3. Compile from source yourself.

**Comment by yanguoyu** [comment]
@doitian 
Apple's M1 is based on `arm`.  `Ckb node` runs success on version 0.103.0. But after the upgrade to 0.104.0, it run failed.
Do you consider support on M1?

0.104.0 run `./ckb --version`
![image](https://user-images.githubusercontent.com/12881040/188437301-8e1366c1-820b-4e7a-bf11-efbace28cb65.png)

0.103.0 run `./ckb --version`
![image](https://user-images.githubusercontent.com/12881040/188437360-63bf09d0-c2c6-4ac4-9bea-6b151d939365.png)

**Comment by doitian** [comment]
I forget we decided to statically linking OpenSSL long time ago. But it stops working because of this

https://github.com/eclipse/paho.mqtt.rust/issues/113#issuecomment-1038265551

See a fixing included in #3578
