### ISSUE TITLE
Add `get_witnesses_proof` RPC

### ISSUE THREAD

**Issue by duanyytop** [nervosnetwork/ckb#3628]
#### Is your feature request related to a problem? Please describe.
I cannot prove that the witnesses of the transaction are in a certain block through CKB RPC.

#### Describe the solution you'd like

If CKB can provide a RPC similar to [get_transaction_proof](https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_transaction_proof) for the witnesses of the transaction, then the existence proof of witnesses can be realized.

**Comment by doitian** [comment]
It's not an easy talk that CKB cannot provide succinct proof of the witnesses' existence based on existing data structure.

@quake any idea about this?

**Comment by doitian** [comment]
Any reason that you cannot provide the whole transaction and the transaction proof in your scenario?

**Comment by duanyytop** [comment]
If the implementation is very complicated, we can consider other solutions, but the current Dapp solutions are making more use of witnesses, so if `get_witnesses_proof` can be provided, it will help Dapp development. 

Regarding the proof of the whole transaction, I wonder if CKB has a solution that can be referenced?

**Comment by doitian** [comment]
Is it enough to provide tx witness hash proof?

**Comment by duanyytop** [comment]
It's ok for us.

**Comment by quake** [comment]
how about adding an optional parameter to `get_transaction_proof` rpc? when it's set to true, we will return the proof of the transaction and witness inclusion in the block:

the result of `includes_witness_proof = true`
```
TransactionAndWitnessProof {
  block_hash: H256
  transactions_proof: MerkleProof
  witnesses_proof: MerkleProof
}
```

the result of  `includes_witness_proof = false`
```
TransactionProof {
  block_hash: H256
  witnesses_root: H256
  proof: MerkleProof
}
```

**Comment by doitian** [comment]
I prefer adding a new RPC. Returning different types based on request parameter makes the documentation generator complex.

**Comment by doitian** [comment]
Assigned to @code-monad
