### ISSUE TITLE
Accelerated Sync attempt

### ISSUE THREAD

**Issue by driftluo** [nervosnetwork/ckb#3668]
As the main network runs longer, the time required for full Sync is gradually increasing, and a new round of Sync optimization begins, we need to find performance bottlenecks to make Sync speed up further and facilitate users to join the network.

Mission focus.
- Finding performance bottlenecks
- Download and commit block async
- Verification parallelization
- Provide a wiki for users to configure themselves to maximize download speed

@eval-exec 

Related PRs: https://github.com/nervosnetwork/ckb/pull/3629
Related wiki: 
- https://github.com/nervosnetwork/ckb/wiki/Synchronization-optimization
- https://github.com/nervosnetwork/ckb/wiki/Deployment-of-ckb

**Comment by eval-exec** [comment]
- Performance bottlenecks
- script group verification parallelization:
    - [x] import rust-rocksdb which contains `get_pined`
    - [x] make `TransactionScriptsVerifier` thread safe
    - [ ] parallelize `TransactionScriptsVerifier::verify()`

**Comment by kfulbright** [comment]
@eval-exec Did you ever get someone to review your PR?

**Comment by eval-exec** [comment]
> @eval-exec Did you ever get someone to review your PR?

Yeah.

**Comment by eval-exec** [comment]
# Analyze Results

On a AWS `c5.xlarge` (4C 8G) machine, I get CPU and IO usage by `pidstat -p $(pidof ckb) -u -p}` 
## CPU Usage
![tmp](https://user-images.githubusercontent.com/46400566/222641800-75cb3b2a-7226-4e10-b1ad-dc7fb7ccf28a.png)

As shown in the figure above, the average CPU usage is `20% ~ 30%`
## IO usage
TODO,
