### ISSUE TITLE
Research UTXO models used in other projects

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3677]
- [ ] Celestia
- [ ] Fuel
- [ ] Cardao EUTXO
- [ ] Sui
- [ ] Ergo
- [ ] ChiaLisp

This research can help the development of #3608

**Comment by xcshuan** [comment]
How about Sui and Ergo?

**Comment by xcshuan** [comment]
In the last comment I misspelled ChiaLisp as ChipLisp.

**Comment by xcshuan** [comment]
[Anoma validity predicates](https://anoma.net/blog/validity-predicates/ )
