### ISSUE TITLE
Guide users to re-sync only when migration fails.

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3683]
#### Is your feature request related to a problem? Please describe.
https://github.com/Magickbase/neuron-public-issues/issues/71#issuecomment-1297020609

The message is misleading. User may think re-sync is faster than migration.

#### Describe the solution you'd like

Remove the following line from the prompt.

```
Another choice is to delete all data, then synchronize them again.
```

Instead, tell users that if the migration fails, try to delete all data and sync again.

**Comment by chenyukang** [comment]
I will fix this trivial issue in https://github.com/nervosnetwork/ckb/pull/4226
