### ISSUE TITLE
Improve Indexer DB options

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb#3696]
Previously, https://github.com/nervosnetwork/ckb/pull/3681 added db options for indexer, but the options of ckb db is not suitable to apply directly to indexer, for example, indexer does not use columns. 

https://discord.com/channels/870891180035031071/871660793333182504/1039794244837187604
A issue was reported, most likely due to the indexer's db compation not being able to keep up, the solution to this is also very simple just set `max_background_compactions`
`max_background_flushes` or `max_background_jobs` can be solved.

**Comment by chenyukang** [comment]
@zhangsoledad this issue is outdate since #3735 is merged, should we close it?

**Comment by zhangsoledad** [comment]
@chenyukang yes
