### ISSUE TITLE
Upgrade SDKs to support CKB v0.106.0

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3726]
RPC changes:

https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-estimate_cycles
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_fee_rate_statics
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_transaction

Related #3710

**Comment by gpBlockchain** [comment]
###  compare 1.0.5~106 
- https://github.com/nervosnetwork/ckb/compare/e0dd357..1674642#diff-6fe1f4e31ab0e32a0eb34735313912f3bf54073b53bb7d67b9af1f41d3f89c44

**Comment by liuck8080** [comment]
according to the code, get_fee_rate_statics, if the target is odd, and it's can be bigger than 101

**Comment by liuck8080** [comment]
> according to the code, get_fee_rate_statics, if the target is odd, and it's can be bigger than 101, should it be a problem?

new issue create for this problem: https://github.com/nervosnetwork/ckb/issues/3755

**Comment by gpBlockchain** [comment]
- https://github.com/nervosnetwork/ckb/commit/0c94c63b0c39d21d3dd10170f242f5223156eab5
