### ISSUE TITLE
Built-in indexer RocksDB filling disk with logs

### ISSUE THREAD

**Issue by gavriilos** [nervosnetwork/ckb#3730]
## Bug Report

The RocksDB for the built-in indexer is filling my disk with logs. Under `~/.ckb/data/indexer/secondary_path/` I had 25 GB accumulated in the `LOG*` files. I also had about 5 GB in the logs under `~/.ckb/data/indexer/store/`.

On the core RocksDB, I was able to control this by setting `keep_log_file_num=1` in the options file (`~/.ckb/default.db-options`). Unfortunately I found no such file for the built-in indexer.

Please provide a way to limit the indexer RocksDB's log files size.

### Environment

- **CKB version**: 0.105.1
- **Chain**: mainnet
- **Operating system**: Ubuntu 20.04
- **Arch**: x64
- **Installation**: GitHub Release

**Comment by driftluo** [comment]
ref: https://github.com/nervosnetwork/ckb/issues/3696

**Comment by chenyukang** [comment]
Closing it since #3735 is merged.
