### ISSUE TITLE
Support Replace-by-fee in memory pool

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3734]
#### Is your feature request related to a problem? Please describe.
CKB only supports Child-pay-for-parent fee-bumping mechanism, but CPFP is not available in some scenarios. For example, when all the cell outputs have a since precondition.

#### Describe the solution you'd like
Add opt-in mechanism to replace a transaction in the memory pool.

- The user must set a flag to show that a transaction can be replaced.
- The new transaction must have a higher fee weight and a total fee amount.

#### References

- https://bitcoincore.org/en/faq/optin_rbf/

**Comment by doitian** [comment]
@code-monad has proposed a solution. We'll hold for now and will push forward when this issue gets enough discussions.

@code-monad could you post your proposal public?

**Comment by code-monad** [comment]
I'll post it here later.

This comment is act as a placeholder.
