### ISSUE TITLE
v0.106.0-rc3 CPU usage is extremely high after the built-in ckb-indexer provides the service

### ISSUE THREAD

**Issue by jiangxianliang007** [nervosnetwork/ckb#3749]
**Translated via DeepL**

### Current Behavior
After v0.106.0-rc3 opened the built-in ckb-indexer module and provided the service to the public, the CPU usage once occupied 30C, fluctuating very much, and fluctuating continuously between 2C-30C, and returned to normal after scheduling the indexer requests to a separate ckb-indexer.

https://testnet.ckb.dev/indexer → ckb rpc cpu exception
https://testnet.ckb.dev/indexer → ckb-indexer rpc normal

### Environment

- **CKB version**: v0.106.0-rc3
- **Chain**: testnet
- **Operating system**: [Ubuntu 20.04, macOS 11.4, Windows 10]
- **Arch**: x64 [the output of `uname -a`]
- **Installation**: [GitHub Release, Built from source]

### Additional context/Screenshots
This is the 36C machine CPU usage graph, the cpu drops instantly at 23:15 after stopping the built-in ckb-indexer requests.
![image](https://user-images.githubusercontent.com/24754263/206607445-ca1c3862-04b1-450f-a149-1e273d637271.png)

<details>
<summary>Original Content in Chinese</summary>

# v0.106.0-rc3  内置的ckb-indexer提供服务后CPU使用率超高

### Current Behavior
v0.106.0-rc3 开启了内置的ckb-indexer 模块，对外提供服务后，CPU 使用率一度占用30C，波动非常大，2C-30C 之间持续波动，将indexer 请求调度到独立的ckb-indexer 后恢复正常。

https://testnet.ckb.dev/indexer → ckb rpc    cpu 异常
https://testnet.ckb.dev/indexer → ckb-indexer rpc 正常

### Environment

- **CKB version**: v0.106.0-rc3
- **Chain**: testnet
- **Operating system**: [Ubuntu 20.04, macOS 11.4, Windows 10]
- **Arch**: x64 [the output of `uname -a`]
- **Installation**: [GitHub Release, Built from source]

### Additional context/Screenshots
这是36C 机器CPU 使用曲线图，23:15 停掉内置ckb-indexer 请求后 cpu 瞬间下降。
![image](https://user-images.githubusercontent.com/24754263/206607445-ca1c3862-04b1-450f-a149-1e273d637271.png)
</details>

**Comment by driftluo** [comment]
may fix by https://github.com/nervosnetwork/ckb/pull/3705

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/3750
