### ISSUE TITLE
rpc api get_fee_rate_statics, if the target is odd, and it's can be bigger than 101

### ISSUE THREAD

**Issue by liuck8080** [nervosnetwork/ckb#3755]
The `MAX_TARGET` is 101, but it is not enforced.
```rust
const MAX_TARGET: u64 = 101;
```

If the target is even, it will increase 1 and check the range, so it will limit to MAX_TARGET. 
https://github.com/nervosnetwork/ckb/blob/develop/rpc/src/util/fee_rate.rs#L76

But if it is odd, it can be very big, even as big as the tip number, so may be it's a problem.

**Comment by quake** [comment]
resolved by https://github.com/nervosnetwork/ckb/pull/3758
