### ISSUE TITLE
exposing system cells info to RPC

### ISSUE THREAD

**Issue by homura** [nervosnetwork/ckb#3781]
#### Is your feature request related to a problem? Please describe.

system cells such as `secp256k1_blake160` are commonly used by developers, but as an application developer, I usually cannot directly base on the machine running the CKB node, so I cannot run `ckb list-hashes`, but guess the system cells by fetching genesis block and hard code the transaction order to resolve system cell's info like this

https://github.com/nervosnetwork/ckb-sdk-rust/blob/850c90da16/src/constants.rs#L19-L22

#### Describe the solution you'd like

If the result of `ckb list-hashes --format json` could be exposed to RPC, it would become more reliable

**Comment by quake** [comment]
the tx index of built-in script are hardcoded and same in the mainnet/testnet/dev chain, you may fetch the genesis block and cache the `CellDep` in your app, for your reference: https://github.com/quake/ckb-ruby-sdk/blob/master/lib/ckb/types/cell_dep.rb#L15-L37

**Comment by homura** [comment]
Okay, so using hardcoded tx order to fetch system cell info is already a working solution, it looks like almost all SDK do this, including JS, Rust, Ruby
