### ISSUE TITLE
Migration of v0.106.0 failed with error code *3221225501*

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/ckb#3853]
### Current Behavior

Migration of v0.106.0 failed with an error code **3221225501**
```log
[2023-02-24 16:03:54.383] [info] CKB migrate:	process exited with code 3221225501
```

And the log file was not generated

### Expected Behavior

Migration succeeds and synchronization starts

### Environment

- **CKB version**: v0.106.0
- **Chain**: mainnet
- **Operating system**: Windows 10
- **Arch**: x64
- **Installation**: Built-in in Neuron

### Additional context/Screenshots

Neuron and the built-in node worked well before the migration because synchronization history could be found in neuron's log, but the `ckb.log` was removed after the migration

**Comment by eval-exec** [comment]
> process exited with code 322122550

Why is the exit code so big?

> [2023-02-24 16:03:54.383] [info] CKB migrate:	process exited with code 3221225501

And this log format does not seem to be generated by `ckb-logger`.

**Comment by Keith-CY** [comment]
> > process exited with code 322122550
> 
> Why is the exit code so big?
> 
> > [2023-02-24 16:03:54.383] [info] CKB migrate:	process exited with code 3221225501
> 
> And this log format does not seem to be generated by `ckb-logger`.

This error code may not be thrown by CKB originally because it can be googled that happens when fail to load ddl

And the format of error message is from Neuron, which proxies error messages from CKB node

Ref: https://github.com/nervosnetwork/neuron/blob/1f19cca93b3247447ab6082eca16021dd6656db6/packages/neuron-wallet/src/services/ckb-runner.ts#L164-L168

**Comment by eval-exec** [comment]
There is an [explaination](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-event-messages#:~:text=WBEM_MC_WBEM_SERVICE_INIT_FAILURE-,3221225501,-(0xC000001D)) of this error code.

**Comment by eval-exec** [comment]
> but the ckb.log was removed after the migration

I want to know why the log file has been deleted. Is it possible that the log data has not been created because of insufficient disk space on your machine？

**Comment by Keith-CY** [comment]
> There is an [explaination](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-event-messages#:~:text=WBEM_MC_WBEM_SERVICE_INIT_FAILURE-,3221225501,-(0xC000001D)) of this error code(`3221225501`) by Microsoft .
> 
> > This could be due to a badly installed version of WMI, WMI repository upgrade failure, insufficient disk space or insufficient memory.
> 
> How much memory/disk space is available on the machine where the migration failed? @Keith-CY
> 
> I suspect this is caused by insufficient memory or insufficient disk space.

This report is from a user of Neuron, I'll check it with him

**Comment by Keith-CY** [comment]
There're 40GB space available on user's computer, so it's probably not caused by insufficient disk space. I have asked the user to run ckb node manually and check the log printed, waiting for response
