### ISSUE TITLE
RpcService method send_transaction error {"code":-302,"message":"TransactionFailedToVerify: Verification failed Script(TransactionScriptError { source: Inputs[2].Type, cause: InvalidCodeHash })"}

### ISSUE THREAD

**Issue by hanzhenlong1314** [nervosnetwork/ckb#3854]
{"version":"0","cell_deps":[{"out_point":{"tx_hash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c","index":"0x0"},"dep_type":"dep_group"},{"out_point":{"tx_hash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c","index":"0x1"},"dep_type":"dep_group"}],"header_deps":[],"inputs":[{"previous_output":{"tx_hash":"0xfad05af0619643716e443c87760c408e9a09d9aef384a3e1096a556e7c817330","index":"0"},"since":"0","capacity":"50078541519"},{"previous_output":{"tx_hash":"0x90ca5231602115d30298e2c4f7c4bf5d1d914dd9c61536b565ff67d5ae9ad32e","index":"0"},"since":"0","capacity":"19900000000"},{"previous_output":{"tx_hash":"0xfeb6e576acdc83738b1c514d1ac3cf49145b4fe317caa1c5eab6156a5aca3aaf","index":"10"},"since":"0","capacity":"13400000000"},{"previous_output":{"tx_hash":"0x9bbc91e676eccc4f806f116703d446301d02c0243d5469d51e0f8a050683ef90","index":"0"},"since":"0","capacity":"11600000000"}],"outputs":[{"capacity":"47489270759","lock":{"code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","args":"0x75ba437eab465d27e076af0dc057a1473f35dd84","hash_type":"type"}},{"capacity":"47488843760","lock":{"code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","args":"0x75ba437eab465d27e076af0dc057a1473f35dd84","hash_type":"type"}}],"outputs_data":["0x","0x"],"witnesses":["0x55000000100000005500000055000000410000007802268426d78e600816c9efeee4b0c636672663b81b42e4ba3d3050600b788c3accb105106058a8f5192cbad081a8dc6f07026d7a596d2be014a739b5ad126a01","0x5500000010000000550000005500000041000000e87956816172e5a1a24f9215809420764145339aed75717f942ef66de6ad591b0f85ac78019fa904ee7995d0a7807e756748a26d2be9f6407d6e9441da17e75601","0x5500000010000000550000005500000041000000b9059f798041449e3273f5fc65021951930acd8138b573b1fef87d3c1ce6ed471bc17f2b981957179abcf18553752cd927b05c29105378f014ba7368184d23b601","0x550000001000000055000000550000004100000057c1eb506c73de2aeeff1e17fbe78b1cadfe5e1ae108bd2d8b8d3f17a2125632120b4faa6e4286996726f20f8bd3b19633cf067fdc71457c07527e16ec2316ca01"]}

This transaction broadcast error, can you help to find out the reason?     RpcService method send_transaction error {"code":-302,"message":"TransactionFailedToVerify: Verification failed Script(TransactionScriptError { source: Inputs[2].Type, cause: InvalidCodeHash })"}

**Comment by driftluo** [comment]
The error reported is `Inputs[2]. Type has InvalidCodeHash`, which means input cell index 2's type script can't find.

inputs[2] is https://explorer.nervos.org/transaction/0xfeb6e576acdc83738b1c514d1ac3cf49145b4fe317caa1c5eab6156a5aca3aaf, it's type script is m-NFT Class, but your transaction's cell_deps didn't include it, so  it cannot be found during verification

**Comment by hanzhenlong1314** [comment]
> The error reported is `Inputs[2]. Type has InvalidCodeHash`, which means input cell index 2's type script can't find.
> 
> inputs[2] is https://explorer.nervos.org/transaction/0xfeb6e576acdc83738b1c514d1ac3cf49145b4fe317caa1c5eab6156a5aca3aaf, it's type script is m-NFT Class, but your transaction's cell_deps didn't include it, so it cannot be found during verification

got it ,thanks
