### ISSUE TITLE
metrics!(gauge) creates histogram metric in prometheus

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3866]
### Current Behavior

The gauge metric added in 
https://github.com/nervosnetwork/ckb/blob/f9cf6db90bc302f840d19727f710c33966b503c1/chain/src/chain.rs#L506 creates the histogram metric in prometheus:

```
# HELP ckb_chain_tip ckb.chain_tip
# TYPE ckb_chain_tip histogram
ckb_chain_tip_bucket{le="0.5"} 0
ckb_chain_tip_bucket{le="0.9"} 0
ckb_chain_tip_bucket{le="0.99"} 0
ckb_chain_tip_bucket{le="+Inf"} 27
ckb_chain_tip_sum 240678864
ckb_chain_tip_count 27
```

### Expected Behavior
It should create a prometheus metric of type gauge.

### Environment

- **CKB version**: ckb 0.108.0-rc2 (f232f87 2023-02-27)
- **Chain**: mainnet
- **Operating system**: macOS 11.4
- **Arch**: x64
- **Installation**: GitHub Release

**Comment by eval-exec** [comment]
I think is should use `value_observer()` instead of `value_recorder`:

https://github.com/nervosnetwork/ckb/blob/19f5362a82da87441daa9ba002a3c4f404cff9de/util/metrics/src/lib.rs#L69-L74

**Comment by doitian** [comment]
After research, it's hard to make gauge work

- The `*_up_down_counter` functions accept the difference between the current and previous values, rather than the last value itself.
- The `*_value_observer` functions utilize a callback to record values, but its lifetime presents a significant challenge when used in macros.

There were two reasons we selected opentelemetry: its thriving community and its tracing capabilities. However, after integrating opentelemetry into CKB, we have yet to use its tracking functionality. Regarding metrics, opentelemetry introduces an abstraction layer that complicates our ability to create the precise Prometheus metric we require. Consequently, I believe we should consider using https://docs.rs/prometheus/latest/prometheus/ instead.

**Comment by eval-exec** [comment]
> I believe we should consider using https://docs.rs/prometheus/latest/prometheus/ instead.

I would like to work on this.

**Comment by eval-exec** [comment]
https://github.com/nervosnetwork/ckb/blob/d3cfcf9be2a8a9271a9174a00efe910fcc509f18/network/src/network.rs#L195-L202

In Prometheus, metrics are evaluated for their uniqueness based on their names and labels.

So I think it's a potential point of high memory consumption, it will cause OOM in the worst case.

**Comment by doitian** [comment]
> https://github.com/nervosnetwork/ckb/blob/d3cfcf9be2a8a9271a9174a00efe910fcc509f18/network/src/network.rs#L195-L202
> 
> In Prometheus, metrics are evaluated for their uniqueness based on their names and labels.
> 
> So I think it's a potential point of high memory consumption, it will cause OOM in the worst case.

Good catch
