### ISSUE TITLE
Type discrepancy in `DeploymentInfo` between codebase and rpc/README.md documentation

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#3951]
The type of `threshold` in `DeploymentInfo` is defined as `Ratio` in the codebase https://github.com/nervosnetwork/ckb/blob/287bc091a8193f28fc89e4ee6514ae0cde3c0876/util/jsonrpc-types/src/info.rs#L47-L73. 

However, in the [rpc/README.md DeploymentInfo](https://github.com/nervosnetwork/ckb/tree/develop/rpc#type-deploymentinfo) file, it is documented as being of type `EpochNumber`, and the `since` field is not yet documented for `DeploymentInfo`.

It appears that there may be an issue with the `./devtools/doc/rpc.py` file.

**Comment by eval-exec** [comment]
In this [PR](https://github.com/nervosnetwork/ckb/pull/3949) , I generate right rpc doc, but it didn't pass the [CI job](https://github.com/nervosnetwork/ckb/actions/runs/4763392552/jobs/8466767683?pr=3949). Also, there appears to be an issue with the CI action.

**Comment by chenyukang** [comment]
The line of 110 could be removed?

https://github.com/nervosnetwork/ckb/blob/develop/Makefile#L110-L111

**Comment by chenyukang** [comment]
Seems there is an issue in `cargo doc`, note the `ratio` part:

![image](https://user-images.githubusercontent.com/230646/233819549-d4e9bc58-e861-4d70-bb02-385cb7537413.png)

Use `cargo +nightly doc` to generate the doc html is OK.

**Comment by eval-exec** [comment]
I think we can use `cargo doc --no-deps` to generate all workspace members, this will generate right cargo doc.

**Comment by chenyukang** [comment]
`cargo +nightly` will change the format of documents, which introduces a lot of differences `rpc/README.md`, there is some existing code to handle this kind of issue:

https://github.com/nervosnetwork/ckb/blob/0c4565b4780d11d252f2d996add2c1e24c5747f7/devtools/doc/rpc.py#L291

HTML is prone to change, we'd better use another solution to generate `rpc/README.md` in the future.

A possible solution is to use `rustdoc` to generate `json` format, such as:
```bash
cargo +nightly rustdoc  -p ckb-fixed-hash  -- -Z unstable-options --output-format json
```

Out of curiosity, why do we generate `rpc/README.md`?

**Comment by eval-exec** [comment]
> `cargo +nightly` will change the format of HTML documents, which introduces a lot of differences `rpc/README.md`, there is some existing code to handle this kind of issue:
> 
> https://github.com/nervosnetwork/ckb/blob/0c4565b4780d11d252f2d996add2c1e24c5747f7/devtools/doc/rpc.py#L291
> 
> HTML is prone to change, we'd better use another solution to generate `rpc/README.md` in the future.
> 
> A possible solution is to use `rustdoc` to generate `json` format, such as:
> 
> ```shell
> cargo +nightly rustdoc  -p ckb-fixed-hash  -- -Z unstable-options --output-format json
> ```
> 
> Out of curiosity, why do we generate `rpc/README.md`?

Cc. @zhangsoledad

**Comment by doitian** [comment]
> Out of curiosity, why do we generate `rpc/README.md`?

Make document close to the code.
