### ISSUE TITLE
Introduce an rpc to query only confirmed transactions

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb#3962]
## Feature Request

The current implementation of the `get_transaction` rpc retrieves the status of a transaction by querying both the store and the tx-pool. However, in scenarios where there is high-pressure on the network, the tx-pool may become highly contested, causing a significant drop in performance for this rpc.

To address this issue, a new `get_confirmed_transaction` rpc could be introduced to retrieve information only about confirmed transactions. This would reduce contention and avoid the performance problems associated with querying the tx-pool. This solution would be useful for users who only need to know whether a transaction has been confirmed or not.

**Comment by eval-exec** [comment]
How about adding a query param `only_confimed: Bool` to `get_transaction`, return confirmed_transaction only when `only_confimed` is `true`.
