### ISSUE TITLE
Define cargo aliases instead of setting them in Makefile

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#3967]
#### Is your feature request related to a problem? Please describe.
We define some complex cargo commands in Makefile, but Makefile does not work well for Windows.

#### Describe the solution you'd like
Define cargo aliases instead. See example here: https://github.com/rust-lang/rust-analyzer/blob/master/.cargo/config.toml

**Comment by eval-exec** [comment]
> Makefile does not work well for Windows.
Which Makefile Entry not work well for Windows? Can cygwin help?

I think defining cargo aliases in `.cargo/config.toml` would increase the maintenance complexity of `Makefile`, as we would need to read both the `Makefile` and `.cargo/config.toml files`.

**Comment by doitian** [comment]
I hope we can remove devtools/windows/make.ps1 from the repo.

**Comment by eval-exec** [comment]
I found https://github.com/matklad/cargo-xtask, cargo-xtask is can help this issue.
