### ISSUE TITLE
The result of returning the number is not hexadecimal.

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/ckb#3978]
### Current Behavior
The `bits` and `threshold` in the returned result are not hexadecimal.
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_consensus
https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-get_deployments_info
<img width="553" alt="image" src="https://github.com/nervosnetwork/ckb/assets/32102187/1ec43baa-76ec-4f05-a4cf-cfdea3c40b7c">
<img width="513" alt="image" src="https://github.com/nervosnetwork/ckb/assets/32102187/a578fb77-c316-4758-9707-784e72e0815f">

**Comment by eval-exec** [comment]
The type of `threshold` field is [type Ratio](https://github.com/nervosnetwork/ckb/tree/develop/rpc#type-ratio), not `type RationalU256`.
