### ISSUE TITLE
Massive `because node is in initial block download` slowdowns looking for the assumed valid target

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/ckb#4009]
### Current Behavior

Looking for the assumed valid target went fast until 3,500,000. The speed was `1900 blocks/s` before  `3,500,000`, then turned to less than `100 blocks/s` because there were massive 

```
2023-06-09 20:39:19.770 +00:00 GlobalRt-2 INFO ckb_sync::synchronizer::get_headers_process  Ignoring getheaders from peer=SessionId(3) because node is in initial block download
```

And this behavior (slowdown after 3,000,000) repeated even the node synced from scratch.

User's case
---
1. speed was around `1900 blocks/s` when block height was `3,360,000`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1584890612
2. re-sync from 0. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1584962672
3. reported that speed dropped dramatically after `3,500,000`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1584979420
4. speed fell to `55 blocks/s` when it reached `4,030,000`, and there were many `because node is in initial block download`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1585513703
5. speed fell to `30 blocks/s` with many `because node is in initial block download`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1585599629
6. resync again to `3,640,000` at a speed of `1158 blocks/s`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1585699939
7. stopped at `3,765,712` with many `because node is in initial block download`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1585702149
8. resynced again and stopped at `4,080,097` with many `because node is in initial block download`, the speed was `83 blocks/s`. comment: https://github.com/nervosnetwork/neuron/issues/2712#issuecomment-1585727396

---

### Expected Behavior

1. Expected to keep the synchronization speed during looking for the assumed valid target.
2. Re-synchronization resolves repeated `because node is in initial block download`

### Environment

- **CKB version**: 0.110.0
- **Chain**: mainnet
- **Operating system**: windows 10
- **Arch**: x64
- **Installation**: Neuron's built-in CKB node

### Additional context/Screenshots

This issue comes from https://github.com/nervosnetwork/neuron/issues/2712

**Comment by eval-exec** [comment]
What's the value of `--assume-valid-target`?
