### ISSUE TITLE
Track segwit SDK and RFC changes

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#407]
* [ ] rfc#0019
* [ ] mruby-contracts https://github.com/nervosnetwork/mruby-contracts/pull/9
* [x] ruby sdk
* [ ] ruby scripts https://github.com/nervosnetwork/ckb-ruby-scripts/pull/10
* [ ] ckb-system-scripts https://github.com/nervosnetwork/ckb-system-scripts/pull/5
* [ ] ruby-demo https://github.com/nervosnetwork/ckb-demo-ruby/pull/78
* [x] swift sdk
* [x] java sdk
* [x] js sdk

_Originally posted by @doitian in https://github.com/nervosnetwork/ckb/pull/368#issuecomment-480659928_

**Comment by Mine77** [comment]
Is rfc#0019 still gonna be updated someday in the future?
