### ISSUE TITLE
Resource utilization of CKB node server.

### ISSUE THREAD

**Issue by guomaoqiu** [nervosnetwork/ckb#4078]
Hi, I need some help with the following questions:

The memory usage of the CKB node server keeps increasing after running for a period of time, although the increase rate is not very noticeable. However, this is a potentially dangerous sign, as there are other services running on the server as well. 

1. Is there no memory release mechanism for this service?
2. If I want to limit its resources, what would be a reasonable allocation of memory/CPU?
3. Apart from restarting the service to release memory, is there any other way to handle this issue?

<img width="745" alt="image" src="https://github.com/nervosnetwork/ckb/assets/9714859/16ef3087-027a-4f7b-a330-d55813d2e1d8">

**Comment by eval-exec** [comment]
Hello, 
What's the version of the ckb node? 
What OS is running the ckb node?
Which tool do you get report the CPU/MEMORY usage?
Is the `public-testnet-ckb-0` is the process name of `ckb`? Or it's the hostname of your machine? Is the `6508Mi` is the sum of all of the process' memory on your machine?
What's the meaning of `50m` below the `CPU(cores)` field? 

Can you show the output of `htop` command?

**Comment by guomaoqiu** [comment]
> Hello, What's the version of the CKB node? And how did you run the CKB node? Which OS is the CKB node running on? Which tool do you use to report the CPU/MEMORY usage? Is `public-testnet-ckb-0` the process name of `ckb`, or is it the hostname of your machine? Is `6508Mi` the sum of all the processes' memory on your machine? What does `50m` below the `CPU(cores)` field mean?
> 
> Could you please show the output of the `htop`, `free -h`, and `hostname` commands?

1. It is a container pod running in Kubernetes, named "public-testnet-ckb-0".
2. The operating system of the host node for Kubernetes is Ubuntu 22.04.1.
3. The container image version of ckb is "nervos/ckb:v0.110.0".
4. The screenshot above shows the result obtained by using the command "kubectl top pod". ":50m" means "50 millicores", which represents 50/1000 of a core.
5. "6508Mi represents the working set size. This is an explanation for monitoring:
```
RSS and WSS are metrics used to represent the memory usage of a process or container. The differences between them are as follows:

RSS (Resident Set Size): Represents the actual physical memory size used by the process, including code, data, heap, stack, and shared libraries. However, RSS does not include memory swapped to disk, so it cannot accurately reflect the actual memory usage of a process.

WSS (Working Set Size): Represents the current memory size being used by the process, including everything in RSS as well as files and caches used by the process. WSS is typically used to measure the actual memory needs of a process for memory allocation and optimization.

Therefore, WSS can more accurately reflect the actual memory usage of a process, but it is typically larger than RSS and changes with the process's running state. In container environments, the 'container_memory_working_set_bytes' metric is typically used to measure the WSS of a container."
```
6. The following is the status of this pod running on the host machine: 
![image](https://github.com/nervosnetwork/ckb/assets/9714859/b437dac5-4492-43d6-988e-19434403035a)
![image](https://github.com/nervosnetwork/ckb/assets/9714859/3a040683-c8f1-407b-a26a-1bce0190fbfd)

**Comment by quake** [comment]
Is your ckb synchronized from height 0, if so, according to your screenshot, it used rss is about 2G, this is normal, generally synchronized from 0, according to different environment, the maximum rss memory will be used between 2.5 ~ 3G.

**Comment by guomaoqiu** [comment]
> 

It's not syncing from 0, it has been running normally for a long time. I'm just wondering why it's using more resources. As you can see from the figure above, the memory usage has been consistently above 4GB.

**Comment by guomaoqiu** [comment]
> It's not syncing from 0, it has been running normally for a long time. I'm just wondering why it's using more resources. As you can see from the figure above, the memory usage has been consistently above 4GB.

"It's not syncing from 0, it has been running normally for a long time. I'm just wondering why it's using more resources. As you can see from the figure above, the memory usage has been consistently above 4GB."

**Comment by eval-exec** [comment]
I suggest to monitor both of `container_memory_working_set_bytes` and `container_memory_rss` metrics. 

https://mohamedmsaeed.medium.com/memory-working-set-vs-memory-rss-in-kubernetes-which-one-you-should-monitor-8ef77bf0acee

**Comment by guomaoqiu** [comment]
> I suggest to monitor both of `container_memory_working_set_bytes` and `container_memory_rss` metrics.
> 
> * https://mohamedmsaeed.medium.com/memory-working-set-vs-memory-rss-in-kubernetes-which-one-you-should-monitor-8ef77bf0acee
> * https://stackoverflow.com/questions/65428558/what-is-the-difference-between-container-memory-working-set-bytes-and-contain
> 
> Could you please show the graph of `container_memory_rss`?

![image](https://github.com/nervosnetwork/ckb/assets/9714859/bace8d9a-99e7-4631-a52d-6ac843de5149)

**Comment by eval-exec** [comment]
Could you please scale the graph's time range to `1 day`, `1 week` and `1 month`?

**Comment by guomaoqiu** [comment]
> Could you please scale the graph's time range to `1 day`, `1 week` and `1 month`?

![image](https://github.com/nervosnetwork/ckb/assets/9714859/c036435e-59e8-4024-846e-c2796a74708c)
![image](https://github.com/nervosnetwork/ckb/assets/9714859/b9da80aa-7a09-4ad3-90b1-201c09127366)
![image](https://github.com/nervosnetwork/ckb/assets/9714859/e46e9d08-812d-46f1-8263-32abcbb4d86d)
（We currently only keep monitoring data for 15 days.)

**Comment by eval-exec** [comment]
In the recent 15 days, the `container_memory_rss` metric did not exceed `3G`, indicating it's currently in a safe range. 


And I read this: [memory measurements on kubernets](https://community.ibm.com/community/user/aiops/blogs/riley-zimmerman/2021/07/02/memory-measurements-complexities-part2?CommunityKey=58f324a3-3104-41be-9510-5b7c413cc48f#:~:text=container_memory_working_set_bytes%20(WSS)%3A%20The%20active,workingSet%20%3A%3D%20ret.Memory.Usage) , learned that "[active cache is counted](https://kubernetes.io/docs/concepts/scheduling-eviction/node-pressure-eviction/#active-file-memory-is-not-considered-as-available-memory) as part of the working set `container_memory_working_set_bytes`. And kubernets will [evicting](https://kubernetes.io/docs/concepts/scheduling-eviction/_print/#pg-78e0431b4b7516092662a7c289cbb304) the pod when under pressure."  

Emm. I recommend setting up an alert to be triggered when the `container_memory_rss` reaches `6G` or `container_memory_working_set_bytes` reaches `12G`.

**Comment by quake** [comment]
The memory usage looks normal, the rss is only about 2.0G according to your graph, I don't think you need to restart ckb service.
