### ISSUE TITLE
Lock the epoch length in a devchain using mainnet data

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb#4092]
#### Background
Currently I'm working on [rescuing dCKB deposits](https://github.com/dckb-rescuer) by writing a new web interface. Given the lack of documentation, it seems impossible to re-deploy correctly those contracts on a brand new devnet.

#### Is your feature request related to a problem? Please describe.
[Following @doitian instructions](https://talk.nervos.org/t/how-to-fork-mainnet-l1-into-a-devnet/7329/5), I'm running a devchain using existing mainnet data.

Now I want to speed up this devnet to test dCKB and NervosDAO interactions, so I followed [the steps previously suggested](https://talk.nervos.org/t/is-there-any-way-to-speed-up-the-blockchain-in-a-way-that-180-epochs-happen-in-a-reasonable-time-frame-in-the-ckb-local-devchain/7163), except for changing the `genesis_epoch_length` as indicated.

The issue is the epoch length doesn't seem much affected by them, as currently one epoch is more than 16 minutes.

 To fully reproduce this issue follow the [steps indicated on the Readme](https://github.com/dckb-rescuer/v1-interface/tree/ed3b384967d24cbbf297ec2a2e41c356bf90668b).

#### Describe the solution you'd like
[@doitian suggested](https://talk.nervos.org/t/how-to-fork-mainnet-l1-into-a-devnet/7329/9): 

> It seems we need a feature to lock the epoch length since a starting epoch for dev environment.

Keep up the great work 💪
Phroi

**Comment by eval-exec** [comment]
Hello, have you tried speeding up the ckb miner? 

You can achieve this by setting lower values for `miner.client.poll_interval` and `miner.workers.value` in `ckb-miner.toml` file , ensuring that `miner.client.poll_interval` is smaller than `miner.workers.value`.

**Comment by phroi** [comment]
@eval-exec the relevant part of `ckb-miner.toml` was like this:
```
[miner.client]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true

# block template polling interval in milliseconds
poll_interval = 1000

# enable listen notify mode
# listen = "127.0.0.1:8888"

[[miner.workers]]
worker_type = "Dummy"
delay_type = "Constant"
value = 200 # instead of 5000
```

**Comment by phroi** [comment]
Now using @eval-exec  `ckb-miner.toml` parameters one epoch is down to 4 minutes :partying_face: 

Still very different from the parameter set in `dev.toml: `epoch_duration_target = 2`

**Comment by eval-exec** [comment]
@phroi I read the [v1-interface's `README.md`](https://github.com/dckb-rescuer/v1-interface/tree/ed3b384967d24cbbf297ec2a2e41c356bf90668b), learned how you start a CKB node. 

The ckb node is based on a mainnet data, `epoch_duration_target = 2` does not affect epoch duration when `permanent_difficulty_in_dummy` is set to `true`.

**Comment by phroi** [comment]
I just tried modifying `permanent_difficulty_in_dummy = false` and running the following command for a few epochs
```bash
(trap 'kill -INT 0' SIGINT; cd ~/ckb_dev/; ./ckb run --skip-spec-check --overwrite-spec --indexer & sleep 1 && ./ckb miner)
```
The epoch length keeps being of constant length 1800 🤔

**Comment by phroi** [comment]
Let me know if you want to try something else :hugs:

**Comment by eval-exec** [comment]
@phroi What's the tip header number/hash of your previous mainnet node?

**Comment by phroi** [comment]
I copied the data folder from my Neuron wallet and **probably** I haven't open it since then :thinking:

This likely is the old tip header information:
```
{
  compactTarget: '0x1908d8ab',
  parentHash: '0xe85526864dd125841e4a416f842e63bbb879c7b2f453ab237cabb69178a568a5',
  transactionsRoot: '0xeff28f2c3ae8997b0c75f4ed1af1445c7895116b3577b9e3edd6369c43b38b06',
  proposalsHash: '0x6853de88d71a10a555e1f7569c738c075c0a8d888db9d7bb37fd528510ebcdeb',
  extraHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
  dao: '0x17f4c23e34d11b4b4ef83f2d25e127002b403a0b9d5577050075de52a0c93307',
  epoch: '0x45f01e5001faa',
  hash: '0xe933e9b52b2c2c56dff489e45b537e7933a43baafae47ca2e6000d91049441cc',
  nonce: '0xdaa23c3d733da1bb00000001ed200209',
  number: '0xa1c649',
  timestamp: '0x189b685192f',
  version: '0x0'
}
```

Parsing the epoch field:
length = 1119
index = 485
number = 8106

The issue is that epoch length now is 1800, but it was 1119 :thinking: :thinking: :thinking:

Side note: when importing the data into the devchain, I was asked to update the database to the new version.

**Comment by eval-exec** [comment]
> The issue is that epoch length now is 1800, but it was 1119 🤔 🤔 🤔

Thank you, I'm trying to reproduce this.

**Comment by eval-exec** [comment]
I've discovered that the maximum value for epoch length is `1800`. I am currently investigating the reasons behind this.

https://github.com/nervosnetwork/ckb/blob/0a3f9b16a1bd2b928b6c82872cfa98ed7b3accc3/spec/src/consensus.rs#L74

**Comment by phroi** [comment]
If it helps solving the issue, I can sync Neuron and we can redo the full procedure together, so we are 100% sure that we are both seeing the same data :hugs:

**Comment by eval-exec** [comment]
> If it helps solving the issue, I can sync Neuron 
Sure.

**Comment by eval-exec** [comment]
> I just tried modifying `permanent_difficulty_in_dummy = false` and running the following command for a few epochs
> 
> ```shell
> (trap 'kill -INT 0' SIGINT; cd ~/ckb_dev/; ./ckb run --skip-spec-check --overwrite-spec --indexer & sleep 1 && ./ckb miner)
> ```
> 
> The epoch length keeps being of constant length 1800 thinking

This behavior aligns with our expectations. When `permanent_difficulty_in_dummy` is set to `false`, CKB's consensus mechanism will dynamically adjust the epoch length and the mining difficulty based on the orphan rate.
https://github.com/nervosnetwork/ckb/blob/0a3f9b16a1bd2b928b6c82872cfa98ed7b3accc3/spec/src/consensus.rs#L847-L852

**Comment by phroi** [comment]
> > If it helps solving the issue, I can sync Neuron
> 
> Sure. I'm syncing my node to latest tip too.

It'll take hours for me:
1. I have a slow connection right now
2. I first have to update to the [latest Neuron wallet 110.2](https://github.com/nervosnetwork/neuron/releases/tag/v0.110.2) (this avoids migrating the database later on)
3. I'll update the blockchain data
4. When I have the previous steps ready, likely tomorrow, I'll let you know

If you have any other question, feel free to ask :hugs:

**Comment by phroi** [comment]
@eval-exec whenever you want I'm ready, also I have updated the node to [`ckb v0.110.0 (Portable)`](https://github.com/nervosnetwork/ckb/releases/tag/v0.110.0)

**Comment by eval-exec** [comment]
> I just tried modifying permanent_difficulty_in_dummy = false ...
> The epoch length keeps being of constant length `1800`

@phroi I have reproduced successfully, and my previous mainnet node's tip header is `10668735`. After ckb miner running for a while, epoch length keeps being of constant `1800`, this is expected because CKB's consensus mechanism.

**Comment by phroi** [comment]
#4097 seems exactly what I had in mind :partying_face:

**Comment by eval-exec** [comment]
> #4097 seems exactly what I had in mind partying_face

If you'd like to give it a try, you can compile this branch of the CKB node yourself. Clone the code from https://github.com/eval-exec/ckb/tree/exec/try-epoch_duration_target, run `make prod`, and you'll get `./target/prod/ckb`.

**Comment by eval-exec** [comment]
@phroi 

I compiled ckb by #4097, and specify `epoch_duration_target = 80` to `specs/dev.toml`, 

`npm run start` complets in 73 seconds:
![image](https://github.com/nervosnetwork/ckb/assets/46400566/a7b86e80-fd40-41a0-8610-3fe69de04c07)


This is my `specs/dev.toml` :
```toml

[params]
genesis_epoch_length = 1743
# Other parameters...
initial_primary_epoch_reward = 1_917_808_21917808
secondary_epoch_reward = 613_698_63013698
max_block_cycles = 10_000_000_000
cellbase_maturity = 0
primary_epoch_reward_halving_interval = 8760
epoch_duration_target = 80 # instead of 14400
permanent_difficulty_in_dummy = true

[pow]
func = "Dummy"
```
and `ckb-miner.toml`:
```toml
[miner.client]
rpc_url = "http://127.0.0.1:8114/"
block_on_submit = true

# block template polling interval in milliseconds
poll_interval = 10

# enable listen notify mode
# listen = "127.0.0.1:8888"

[[miner.workers]]
worker_type = "Dummy"
delay_type = "Constant"
value = 10

```

**Comment by phroi** [comment]
I tried to reproduce all steps from zero, but ckb node kept crashing. So I standardized and repeated all steps again and again until I remembered that on this old laptop I have to use ckb **Portable**, so `make prod_portable`... Understood that, it was smooth ride!! :muscle:

I confirm that #4097 solves this issue, feel free to close this issue when the PR gets merged!

Thanks for your support @eval-exec :hugs:
Phroi

**Comment by doitian** [comment]
A new RPC method will be added to ease generating an epoch: https://github.com/nervosnetwork/ckb/pull/4128
