### ISSUE TITLE
Upgrade outdated crates

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#41]
## Outdated

- [x] parking_lot 0.7.0
- [x] crossbeam-channel 0.3.2 @quake 
- [x] env_logger 0.6.0
- [x] rand 0.6.1
- [x] indicatif 0.10.1
- [x] tokio 0.1.11 -> 0.1.13

**Comment by doitian** [comment]
The crate `parking_lot` depends on `rand`. The crate `rand` upgrade seems to break many codes.

**Comment by zhukevin** [comment]
test

**Comment by zhangsoledad** [comment]
- [ ] tokio 0.1.11 -> 0.1.13

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/50
