### ISSUE TITLE
Generate Open RPC specification

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#4149]
#### Is your feature request related to a problem? Please describe.

[Open RPC](https://open-rpc.org/) is [Open API](https://www.openapis.org/) for JSON RPC.

Generating the OPEN RPC specification allows user to try the RPC methods in the [playground](https://playground.open-rpc.org/).

#### Describe the solution you'd like
Generating the Open RPC specification from the code or from rpc/README.md

**Comment by eval-exec** [comment]
We need this feature, and I prefer the web UI design by [rapidocweb](https://rapidocweb.com/examples/example1.html).

**Comment by doitian** [comment]
> We need this feature, and I prefer the web UI design by [rapidocweb](https://rapidocweb.com/examples/example1.html).

Open API does not play well with JSON RPC

**Comment by eval-exec** [comment]
How about swagger: https://dev.to/vearutop/json-rpc-2-0-with-swagger-ui-2h3g

**Comment by eval-exec** [comment]
Why Open API not play well with JSON-RPC?

I found this: https://cronos.org/swagger/jsonrpc.json. The ethereum JSON-RPC schema are defined by Open API, and they provide documented it by swagger, looks better than Open RPC's web UI.: https://cronos.org/swagger?network=mainnet#/ETH%20Methods/eth_accounts
