### ISSUE TITLE
Static build CKB's release with `openssl 3` 

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4159]
#### Is your feature request related to a problem? Please describe.

The OpenSSL 1.1.1 series has reached its [End of Life](https://www.openssl.org/blog/blog/2023/09/11/eol-111), so it's time for us to transition to OpenSSL 3 since CKB is statically built with OpenSSL 1.1.1.

https://github.com/nervosnetwork/ckb/blob/6c6ea88c7605aaed1f955485205745dd9cb0fa0c/.github/workflows/package.yaml#L113-L115

https://github.com/nervosnetwork/ckb/blob/6c6ea88c7605aaed1f955485205745dd9cb0fa0c/.github/workflows/package.yaml#L198

https://github.com/nervosnetwork/ckb/blob/6c6ea88c7605aaed1f955485205745dd9cb0fa0c/.github/workflows/package.yaml#L257

We should also consider upgrading the `ckb-docker-builder`:

https://github.com/nervosnetwork/ckb-docker-builder/blob/8ce6f4d4a073be833ef07f6a61d038eeb12b5780/centos-7/Dockerfile#L11-L12

**Comment by doitian** [comment]
Related: https://github.com/nervosnetwork/ckb-cli/issues/566

**Comment by eval-exec** [comment]
We can't use `centos-7` to build `openssl 3.1.3`, since `openssl 3.1.3` need `GLIBC_2.18` at least, but `centos-7` only provide `GLIBC 2.17`:

- When I try to build openssl 3.1.3 on [nervos/ckb-docker-builder:centos-7-rust-1.71.1](https://github.com/nervosnetwork/ckb-docker-builder/blob/master/centos-7/Dockerfile), this error occured:
```bash
Caused by:
  process didn't exit successfully: `/ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main` (exit status: 1)
  --- stderr
  /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main)
  /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main)
  /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /ckb/target/prod/build/openssl-sys-9f0e66e82e308245/build-script-main)
warning: build failed, waiting for other jobs to finish...
error: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /ckb/target/prod/deps/libnumext_constructor-034cd93ffbc6e1e3.so)
```

```bash
❯ docker run --rm -it nervos/ckb-docker-builder:centos-7-rust-1.71.1 bash                                 
[root@9574b0e79d5a /]# ldd --version
ldd (GNU libc) 2.17
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by doitian** [comment]
try newer version of devtoolset and llvm-toolset

**Comment by eval-exec** [comment]
> try newer version of devtoolset and llvm-toolset

Thank you.

**Comment by eval-exec** [comment]
@doitian I just found out that the easiest way to make ckb binary statically link SSL is to enable the openssl-vendored feature of the tentacle package.

**Comment by eval-exec** [comment]
If we enable `openssl-vendored` feature for tentacle, then we won't need to compile openssl in `ckb-docker-builder` anymore.
