### ISSUE TITLE
Replacement solution needed for slow "DB Migration" operation

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4162]
The current implementation of CKB requires a time-consuming "DB migration" operation when the [db-schema](https://github.com/nervosnetwork/ckb/blob/develop/db-schema/src/lib.rs) is changed. This process can take up to 6-7 hours for 30M blocks of CKB. We need to find a faster and more efficient solution for this task.

**Comment by doitian** [comment]
A lazy update mechanism may help.

- Do not migrate existing data. Use a flag in the new schema to indicate the data version.
- When read a value from the db, and it uses an old version, migrate on the fly and save back the migrated value.

**Comment by chenyukang** [comment]
close this issue since #4226 is merged.
