### ISSUE TITLE
Easy daemon mode for ckb run

### ISSUE THREAD

**Issue by CipherWang** [nervosnetwork/ckb#4237]
#### Is your feature request related to a problem? Please describe.
There is no simple approach to run a ckb node in daemon or background mode. Although there is an introduction to [start a ckb service](https://github.com/nervosnetwork/ckb/tree/develop/devtools/init), it's still too complex for average users.

#### Describe the solution you'd like
Similar to bitcoind, if ckb run provide a simple switch like `ckb run --daemon`, I believe more nodes will appear.

**Comment by eval-exec** [comment]
I read [bitcoind daemon mode](https://bitcoin.stackexchange.com/questions/74116/bitcoind-daemon-mode), learned that: `bitcoind --daemon` just run `bitcoind` in background, it won't auto start after system reboot.

However, using `systemd` can make the process restarts automatically after a reboot

**Comment by janx** [comment]
But assume the existence of `systemd` reduce daemon mode's compatibility? e.g. does it work on Mac?

**Comment by eval-exec** [comment]
MacOS doesn't have `systemd`, the quivalent of systmed on MacOS is called [launchd](https://apple.stackexchange.com/questions/455362/equivalent-to-systemd-timers-on-os-x)
