### ISSUE TITLE
"code":-302,"message":"TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) \u003c\u003d capacity (0x3b9aca00))"}invoke io error

### ISSUE THREAD

**Issue by hanzhenlong1314** [nervosnetwork/ckb#4261]
Hello, broadcast error, "code":-302,"message":"TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) \u003c\u003d capacity (0x3b9aca00))"}invoke io error, can you help me find out why?

the broadcast data is：

{"version":"0","cell_deps":[{"out_point":{"tx_hash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c","index":"0x0"},"dep_type":"dep_group"},{"out_point":{"tx_hash":"0x71a7ba8fc96349fea0ed3a5c47992e3b4084b031a42264a018e0072e8172e46c","index":"0x1"},"dep_type":"dep_group"}],"header_deps":[],"inputs":[{"previous_output":{"tx_hash":"0x6cc65cb7828db7012b7b30a0b3c6015e988224ae1703e60207a815aa229f5a93","index":"1"},"since":"0","capacity":"2784059195573821"}],"outputs":[{"capacity":"1000000000","lock":{"code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","args":"0x5375c3a7d7911585fbee5c7fb29e1bbf32965dd1","hash_type":"type"}},{"capacity":"2784058195278821","lock":{"code_hash":"0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8","args":"0x5bc215a42a4c2b03db6cfd25cec732ecc5bbadee","hash_type":"type"}}],"outputs_data":["0x","0x"],"witnesses":["0x5500000010000000550000005500000041000000469bc750ef69d7f70ff555cf0acee05393ab32ddddfb788453df8e0113b757d73df00e7a3ec7db0fabf8966d734af9b7721e43452d1940e06103279f2701f7bb00"]}

**Comment by eval-exec** [comment]
> `TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) \u003c\u003d capacity (0x3b9aca00))` 

Actualy, this this:
```
TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) <= capacity (0x3b9aca00))
```

It means the capacity of outputs[0] (`1000000000`) is less than the min capacity required to create a cell (`6100000000`).

Ref: **[the minimum transfer amount cannot be less than 61 CKB](https://docs.nervos.org/docs/integrate/qa/#:~:text=Why%20is%20it%20that%20the%20minimum%20transfer%20amount%20cannot%20be%20less%20than%2061%20CKB%3F)**

**Comment by hanzhenlong1314** [comment]
> > `TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) \u003c\u003d capacity (0x3b9aca00))`
> 
> Actualy, this this:
> 
> ```
> TransactionFailedToVerify: Verification failed Transaction(InsufficientCellCapacity(Outputs[0]): expected occupied capacity (0x16b969d00) <= capacity (0x3b9aca00))
> ```
> 
> It means the capacity of outputs[0] (`1000000000`) is less than the min capacity required to create a cell (`6100000000`).
> 
> Ref: **[the minimum transfer amount cannot be less than 61 CKB](https://docs.nervos.org/docs/integrate/qa/#:~:text=Why%20is%20it%20that%20the%20minimum%20transfer%20amount%20cannot%20be%20less%20than%2061%20CKB%3F)**

got it，thanks

**Comment by hanzhenlong1314** [comment]
solved
