### ISSUE TITLE
`No connection could be made because the target machine actively refused it. (os error 10061)` occurred on the Windows CI workflow

### ISSUE THREAD

**Issue by eval-exec** [nervosnetwork/ckb#4281]
### Current Behavior
Windows CI workflow failed:
https://github.com/nervosnetwork/ckb/actions/runs/7330344503/job/19961292989
It appears to be related to https://github.com/nervosnetwork/ckb/pull/4245

**Comment by chenyukang** [comment]
why #4245 was merged successfully if the CI failed...

**Comment by eval-exec** [comment]
> why #4245 was merged successfully if the CI failed...

Maybe related to https://github.com/nervosnetwork/ckb/pull/3837

**Comment by chenyukang** [comment]
Fixed by #4287 .
