### ISSUE TITLE
Method not allowed for HTTP OPTIONS request.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb#4310]
## Bug Report

Starting with v0.113.0, the RPC no longer allows OPTIONS requests. This was available in v0.112.1.

This prevents web browsers from properly interacting with the RPC.

### Environment

- **CKB version**: v0.113.0
- **Chain**: testnet & mainnet
- **Operating system**: Ubuntu 20.04
- **Arch**: x64
- **Installation**: GitHub Release

### Additional context/Screenshots
![20240119224031](https://github.com/nervosnetwork/ckb/assets/37931/09d737ac-a707-4146-8eed-08c7ea94339d)

**Comment by quake** [comment]
a known issue, resolved by https://github.com/nervosnetwork/ckb/pull/4307, will release a bug fix version next week.

**Comment by jordanmack** [comment]
Confirmed as fixed in v0.113.1.
