### ISSUE TITLE
CKB Node upgrade from v0.112.1 to v0.113.0 unsuccessful with existing configuration.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb#4312]
## Bug Report

Attempting to upgrade my v0.112.1 CKB nodes to v0.113.0 without making any changes to the configuration files was not successful. The v0.113.0 node starts up but never seems to catch up. The upgrade was done by replacing the old binary with the new binary, without changing anything in the configuration. I did not see any instructions on the release screen about config changes necessary for the update.

Errors such as this are visible in the logs:

```txt
Jan 20 07:15:24 dev5 ckb[3938175]: 2024-01-20 07:15:24.495 +00:00 GlobalRt-1 ERROR ckb_network::protocols::identify  Disconnect IdentifyProtocol session SessionContext { id: SessionId(353), address: "/ip4/35.183.172.68/tcp/8114/p2p/QmNRAvtC6L85hwp6vWnqaKonJw3dz1q39B4nXVQErzC4Hx", ty: Outbound, remote_pubkey: Some(0x0392d609c02ebf918129073ba6623ae2de1a25e4b34989d4ab825648e97c733a58), closed: false, pending_data_size: 0 } due to invalid identify message.
Jan 20 07:15:24 dev5 ckb[3938175]: 2024-01-20 07:15:24.944 +00:00 GlobalRt-0 WARN ckb_network::protocols::identify  IdentifyProtocol detects peer has different network identifiers, local network id: /ckb_testnet/10639e08, remote network id: /ckb/92b197aa
Jan 20 07:15:24 dev5 ckb[3938175]: 2024-01-20 07:15:24.944 +00:00 GlobalRt-0 INFO ckb_network::network  Ban peer "/ip4/3.105.209.193/tcp/8114/p2p/QmQidJaxciY3NT2PjsaCR4Gz8vB8kFn3Avwz96u6b3jGc1" for 300 seconds, reason: The nodes are not on the same network
Jan 20 07:15:24 dev5 ckb[3938175]: 2024-01-20 07:15:24.944 +00:00 GlobalRt-0 ERROR ckb_network::protocols::identify  Disconnect IdentifyProtocol session SessionContext { id: SessionId(354), address: "/ip4/3.105.209.193/tcp/8114/p2p/QmQidJaxciY3NT2PjsaCR4Gz8vB8kFn3Avwz96u6b3jGc1", ty: Outbound, remote_pubkey: Some(0x02ab0a6a60dd66178ca56037f682b163cdcb77d8f1a8a155a917caf812d3f69185), closed: false, pending_data_size: 0 } due to invalid identify message.
```

Generating a new configuration with `ckb init --chain testnet`, but keeping the existing `data` folder, appeared to fix the problem.

### Environment

- **CKB version**: v0.113.0
- **Chain**: testnet
- **Operating system**: Ubuntu 20.04
- **Arch**: Linux dev5 5.15.108-1-pve #1 SMP PVE 5.15.108-2 (2023-07-20T10:06Z) x86_64 x86_64 x86_64 GNU/Linux
- **Installation**: GitHub Release

### Additional context/Screenshots

[testnet-updated-node.log.zip](https://github.com/nervosnetwork/ckb/files/13997106/testnet-updated-node.log.zip)

**Comment by quake** [comment]
```
Jan 20 07:15:24 dev5 ckb[3938175]: 2024-01-20 07:15:24.944 +00:00 GlobalRt-0 WARN ckb_network::protocols::identify  IdentifyProtocol detects peer has different network identifiers, local network id: /ckb_testnet/10639e08, remote network id: /ckb/92b197aa
```

This error indicates that the remote node is a mainnet network node, which network id starts with mainnet genesis hash. did you copy the peerstore data from mainnet node folder accidentally?

**Comment by jordanmack** [comment]
> This error indicates that the remote node is a mainnet network node, which network id starts with mainnet genesis hash. did you copy the peerstore data from mainnet node folder accidentally?

I don't know how that would have happened, but I suppose I cannot rule out a mistake since I was copying data. It's not possible for me to verify what was in the peer folder since I don't have a copy any longer, but I do have the exact steps I used to fix it from the Bash history.

You can see on line 57 where I generate a new configuration and copy the files. This seemed to fix it. I never touched anything in the data folder.

```
   42  wget https://github.com/nervosnetwork/ckb/releases/download/v0.113.0/ckb_                                                                                                                                                             v0.113.0_x86_64-unknown-linux-gnu.tar.gz
   43  tar xzf ckb_v0.113.0_x86_64-unknown-linux-gnu.tar.gz
   44  cp ckb_v0.113.0_x86_64-unknown-linux-gnu/ckb* ckbt/
   45  rm -rf ckb_v0.113.0_x86_64-unknown-linux-gnu
   46  rm -rf ckb_v0.113.0_x86_64-unknown-linux-gnu.tar.gz
   47  ls
   48  systemctl start ckb-testnet
   49  journalctl -fu ckb-testnet
   50  ./ckbt/ckb -V
   51  journalctl -fu ckb-testnet
   52  ls
   53  journalctl -fu ckb-testnet
   54  uname -a
   55  journalctl -fu ckb-testnet
   56  ls
   57  systemctl stop ckb-testnet
   58  cd ckbt
   59  mkdir test
   60  cd test
   61  ../ckb init --chain testnet
   62  ls
   63  cp ./ckb* ..
   64  cp default.db-options ..
   65  cd ..
   66  rm -rf test/
   67  nano ckb.toml
   68  systemctl start ckb-testnet
```
