### ISSUE TITLE
`get_fee_rate_statistics` returns apparently incorrect data on devnet

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb#4350]
Hello folks at Nervos,
I'm running a [devnet for testing iCKB](https://github.com/ickb/v1-core?tab=readme-ov-file#environment-setup) and I see an unexpected behavior.

### Current Behavior
I have a stream of transactions with 1000 feeRate, but then when I check `get_fee_rate_statistics` both mean and median feeRate seems almost double. So went back to my code, I double checked and my transactions indeed have the intended feeRate, I'm not overpaying.

Also I tried increasing the feeRate to 10^9, but `get_fee_rate_statistics` consistently returns around double of the intended fee rate.

Also I tried setting feeRate to 999 and indeed the txPool reject the transaction as expected.

### Expected Behavior
`get_fee_rate_statistics` should return feeRate mean and median of the past transactions feeRate.

### Environment

- **CKB version**: ckb 0.113.0 (82871a3 2024-01-09)
- **Chain**: dev
- **Operating system**: Ubuntu 20.04
- **Arch**: x86_64
- **Installation**: GitHub Release

**Comment by phroi** [comment]
Just tested: `fee_rate` still explodes on devnet :man_shrugging:

**Comment by eval-exec** [comment]
> Just tested: `fee_rate` still explodes on devnet :man_shrugging:

Sorry, this right fix will be in 0.119.0
https://github.com/nervosnetwork/ckb/pull/4654

**Comment by eval-exec** [comment]
Ref: https://github.com/nervosnetwork/ckb/releases/tag/v0.119.0

**Comment by eval-exec** [comment]
I think we can close this issue.
