### ISSUE TITLE
Export more RPC methods to make OTX pool easier

### ISSUE THREAD

**Issue by xcshuan** [nervosnetwork/ckb#4397]
### Is your feature request related to a problem? Please describe.
When designing applications based on open_transaction, the application side may need to determine the validity of the OTX. However, since the OTX is not yet complete at this time, it cannot use the CKB node to verify the correctness of the OTX. Therefore, it is necessary for the CKB node to expose some new rpc methods, allowing the application side to maintain its own OTX Pool.

### Describe the solution you'd like
More rpc methods should be added, such as determining whether an outpoint is a live_cell, and whether an outpoint has transactions in the tx pool, what the transaction hash and some transaction information are.

**Comment by doitian** [comment]
CKB can only verifiy the seal in the OTX.

There are already two RPC methods to dry run a transaction:

- [`estimate_cycles`](https://github.com/nervosnetwork/ckb/tree/develop/rpc#chain-estimate_cycles)
- [`dry_run_transaction`](https://github.com/nervosnetwork/ckb/tree/develop/rpc#method-dry_run_transaction)

Both will run all the script groups. To support OTX, I recommend adding a method to run only selected script groups (by lock type and lock script hash), or return the running result for each script group seperately. To verify OTX, we can check whether all the lock script groups pass.

**Comment by xcshuan** [comment]
In addition, it is also important to know whether an outpoint is live and whether it exists in the memory pool.

**Comment by zhangsoledad** [comment]
https://github.com/nervosnetwork/ckb/pull/4433

**Comment by doitian** [comment]
> #4433

This is not enough, since for an open tx the type script groups may fail and it's OK they fail.
