### ISSUE TITLE
CKB v114.0 Full node sync is stopped.

### ISSUE THREAD

**Issue by silySuper** [nervosnetwork/ckb#4462]
## Bug Report

Full node sync is stopped.

### Current Behavior
<img width="1438" alt="截屏2024-05-15 10 07 34" src="https://github.com/nervosnetwork/ckb/assets/25971273/18069cf4-14a4-4cd9-859f-2a187aeebbca">
[logs 2.zip](https://github.com/nervosnetwork/ckb/files/15315402/logs.2.zip)

<img width="1018" alt="截屏2024-05-15 10 09 17" src="https://github.com/nervosnetwork/ckb/assets/25971273/3787cc2d-adc0-4b0d-9bd8-6906e4681aeb">

### Environment

- **CKB version**: v114.0
- **Chain**: testnet

testnet/data has been replaced by https://download.magickbase.com/backup_20240513.tar.gz

**Comment by eval-exec** [comment]
When you say, "Full node is stopped," do you specifically mean that the CKB has been synchronizing for a long time but the block height hasn't increased?

Could you provide the output of:
```bash
curl -X POST 127.0.0.1:8114 -H 'Content-Type: application/json' -d '{ "id": 42, "jsonrpc": "2.0", "method": "sync_state", "params": [ ] }'
```
and 
```bash
curl -X POST 127.0.0.1:8114 -H 'Content-Type: application/json' -d '{ "id": 42, "jsonrpc": "2.0", "method": "get_peers", "params": [ ] }'
```

**Comment by silySuper** [comment]
It has been sync from yesterday afternoon to now.
<img width="693" alt="截屏2024-05-15 10 50 51" src="https://github.com/nervosnetwork/ckb/assets/25971273/1c86715c-d425-4f32-9b3a-ab05678698c5">
<img width="922" alt="截屏2024-05-15 10 51 09" src="https://github.com/nervosnetwork/ckb/assets/25971273/56b1aea4-8e84-4224-907a-502a3247bd12">

**Comment by eval-exec** [comment]
1. Did you modify the default ckb.toml file? How?
2. Could you provide the full log file?

**Comment by silySuper** [comment]
[run.log](https://github.com/nervosnetwork/ckb/files/15315800/run.log)


 I do not change ckb.toml.This part of ckb.toml.
### Whitelist-only mode
# whitelist_only = false
### Whitelist peers connecting from the given IP addresses
# whitelist_peers = []
### Enable `SO_REUSEPORT` feature to reuse port on Linux, not supported on other OS yet
# reuse_port_on_linux = true

max_peers = 125
max_outbound_peers = 8
# 2 minutes
ping_interval_secs = 120
# 20 minutes
ping_timeout_secs = 1200
connect_outbound_interval_secs = 15
# If set to true, try to register upnp
upnp = false
# If set to true, network service will add discovered local address to peer store, it's helpful for private net development
discovery_local_address = false
# If set to true, random cleanup when there are too many inbound nodes
# Ensure that itself can continue to serve as a bootnode node
bootnode_mode = false

**Comment by eval-exec** [comment]
I found there are some ERROR in `run.log`:
```
2024-05-14 20:18:58.451 +00:00 log flusher ERROR sled::flusher  failed to fsync from periodic flush thread: Input/output error (os error 5)
```
1. What happened in `2024-05-14 20:18:58.451`?
2. Could you provide:
```bash
curl -X POST 127.0.0.1:8114 -H 'Content-Type: application/json' -d '{ "id": 42, "jsonrpc": "2.0", "method": "get_banned_addresses", "params": [ ] }'
```

**Comment by silySuper** [comment]
1.At 2024-05-14 20:18:58.451 ,computer is sleeping(v114.0 is in my hard disk).
2.
[addr_manager.db.zip](https://github.com/nervosnetwork/ckb/files/15316935/addr_manager.db.zip)
[ban_list.db.zip](https://github.com/nervosnetwork/ckb/files/15316938/ban_list.db.zip)

3.
<img width="789" alt="截屏2024-05-15 14 07 12" src="https://github.com/nervosnetwork/ckb/assets/25971273/57878708-7578-421d-90d7-c7f172c46e29">
<img width="857" alt="截屏2024-05-15 14 11 55" src="https://github.com/nervosnetwork/ckb/assets/25971273/7e0b39a5-62b1-42bd-9299-a0ad800f31a5">

**Comment by silySuper** [comment]
<img width="567" alt="截屏2024-05-15 14 40 28" src="https://github.com/nervosnetwork/ckb/assets/25971273/0f3faefc-c3fd-4727-a4c2-f258bcdeca82">
now it shows error in ckb server.

**Comment by eval-exec** [comment]
Could you change `[loggger].filter` to `"debug"` in ckb.toml, then restart ckb node, then provide the log file?

**Comment by silySuper** [comment]
My hard drive does not throw error before，I will find  a tool to check whether it is malfunctioning
[logs.zip](https://github.com/nervosnetwork/ckb/files/15317805/logs.zip)

**Comment by eval-exec** [comment]
What's the configuration for `support_protocols` in your `ckb.toml` file?

Could you share the complete configuration from your `ckb.toml` file?

**Comment by eval-exec** [comment]
I found your node is buzy on serving a RPC:
```bash
❯ cat logs/run.log | grep -i rpc | head
2024-05-15 07:21:02.362 +00:00 main INFO ckb_rpc::server  Listen HTTP RPCServer on address: 127.0.0.1:8114
2024-05-15 07:21:02.944 +00:00 GlobalRt-7 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0xc9ed7d","id":8362}.
2024-05-15 07:21:02.953 +00:00 GlobalRt-6 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606","id":8716}.
2024-05-15 07:21:02.964 +00:00 GlobalRt-6 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"alerts":[],"chain":"ckb_testnet","difficulty":"0x1c794aac","epoch":"0x70800e40021fd","is_initial_block_download":true,"median_time":"0x18f70071de4"},"id":2884}.
2024-05-15 07:21:02.971 +00:00 GlobalRt-0 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606","id":1528}.
2024-05-15 07:21:02.972 +00:00 GlobalRt-6 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"alerts":[],"chain":"ckb_testnet","difficulty":"0x1c794aac","epoch":"0x70800e40021fd","is_initial_block_download":true,"median_time":"0x18f70071de4"},"id":2529}.
2024-05-15 07:21:02.975 +00:00 GlobalRt-6 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x10639e0895502b5688a6be8cf69460d76541bfa4821629d86d62ba0aae3f9606","id":3712}.
2024-05-15 07:21:03.926 +00:00 GlobalRt-0 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0xc9ed7d","id":804}.
2024-05-15 07:21:04.931 +00:00 GlobalRt-4 DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0xc9ed7d","id":8224}.
2024-05-15 07:21:05.190 +00:00 GlobalRt-6 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"compact_target":"0x1d08fda0","dao":"0xa58aea41d2aa324d7444ff8c4625280007bc9da5479673060085b8d95c40d408","epoch":"0x70800e40021fd","extra_hash":"0x167c593d80e706b9c2e52c9a6aeebf39fdd08574c55b6deb5df128a1484677cb","hash":"0xf47a17392103d8c423089c6fb42ea3bd15cd44b5a8268c7ae18a72d517906ce2","nonce":"0xc108f9e52219af493fa13978b8cb7429","number":"0xc9ed7d","parent_hash":"0xcdc8fe751ae2731595b674b07f116ab240eefde45b4a911e702b79f58cffc441","proposals_hash":"0xf6d454599fdf28e3c73fb8e7d0d93e3f6128ad650a21b0f745cb9fba8bb0742f","timestamp":"0x18f70094a66","transactions_root":"0x9ff138b4bd1cbb83065343651537ac465209abb26455f0dd603978c6447ea6f4","version":"0x0"},"id":3662}.
/tmp/t
❯ cat logs/run.log | grep -i rpc | tail
2024-05-15 07:22:08.718 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":3306}.
2024-05-15 07:22:08.719 +00:00 GlobalRt-8 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":7302}.
2024-05-15 07:22:08.719 +00:00 GlobalRt-8 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":9305}.
2024-05-15 07:22:08.719 +00:00 GlobalRt-8 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":8167}.
2024-05-15 07:22:08.720 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":3193}.
2024-05-15 07:22:08.721 +00:00 GlobalRt-8 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":4394}.
2024-05-15 07:22:08.721 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":3780}.
2024-05-15 07:22:08.721 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":285}.
2024-05-15 07:22:08.722 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":3175}.
2024-05-15 07:22:08.723 +00:00 GlobalRt-1 DEBUG rpc  Response: {"jsonrpc":"2.0","result":{"last_cursor":"0x","objects":[]},"id":8217}.
/tmp/t
❯ cat logs/run.log | grep -i rpc | wc -l
116692
```

**Comment by silySuper** [comment]
<img width="398" alt="截屏2024-05-15 16 51 22" src="https://github.com/nervosnetwork/ckb/assets/25971273/f6db18e6-df69-4f21-bac6-dd036aea0f33">
 I does not find any other rpc requests to the ckb node.

<img width="893" alt="截屏2024-05-15 16 52 50" src="https://github.com/nervosnetwork/ckb/assets/25971273/ccc7a4dc-eed6-4ce7-9bcc-89aea97afca3">

**Comment by eval-exec** [comment]
> I does not find any other rpc requests to the ckb node. 


How about change `[network].listen_addresses` to another port, and restart?

**Comment by silySuper** [comment]
chang port 8115 to 8117 and restart
<img width="566" alt="截屏2024-05-15 17 27 13" src="https://github.com/nervosnetwork/ckb/assets/25971273/e41cf319-b8d1-444c-9982-f8ea7438cf06">
the same

**Comment by quake** [comment]
> > I does not find any other rpc requests to the ckb node.
> 
> How about change `[network].listen_addresses` to another port, and restart?

I think it should be `[rpc].listen_address`

**Comment by silySuper** [comment]
change from 8114 to 8115
<img width="1136" alt="截屏2024-05-15 18 36 20" src="https://github.com/nervosnetwork/ckb/assets/25971273/dead4c57-0043-4748-9cf5-cdac8c7c5c09">

**Comment by eval-exec** [comment]
> change from 8114 to 8115 

Has the height of the ckb node increased after an hour has passed?
Is the Neron client currently connected to this ckb node? Could you try shutting down the Neron client and directly launching the ckb node?

**Comment by silySuper** [comment]
after change port,it always shows connecting,so I change to port 8114 again.I want to try v115 ,but it always show not safe even I clicked allowed in Privacy and security of my computer.Whether we can find a faster way to solve this?because it has blocked me for about two weeks.

**Comment by silySuper** [comment]
step 1.
<img width="1162" alt="截屏2024-05-16 09 49 36" src="https://github.com/nervosnetwork/ckb/assets/25971273/2a6c21bf-a5da-4cee-ae29-92bc787c4704">

step 2.
<img width="501" alt="截屏2024-05-16 09 49 48" src="https://github.com/nervosnetwork/ckb/assets/25971273/c3bb7ade-ba3b-474a-b03a-e987e5f2590a">

step 3.

<img width="1120" alt="截屏2024-05-16 09 50 50" src="https://github.com/nervosnetwork/ckb/assets/25971273/755ef2ec-8c09-4b06-b210-920c382df39c">

**Comment by eval-exec** [comment]
I'm sorry, I don't have experience with Mac. Would this link to Apple support be helpful? 
[Apple 无法检查 App 是否包含恶意软件](https://support.apple.com/zh-cn/guide/mac-help/mchleab3a043/mac)

**Comment by silySuper** [comment]
I operate already,it does not effect.

**Comment by eval-exec** [comment]
> after change port,it always shows connecting

Could you try starting the ckb process after shutting down the Neoron client?

**Comment by eval-exec** [comment]
> Whether we can find a faster way to solve this?because it has blocked me for about two weeks.


Do you know the absolute path of the ckb 0.114.0 binary file?
Could you copy the previous `data/db` file, initialize ckb in a new directory, and try again?
1. Initialize ckb configurations in a new_dir
```bash
./ckb init -C new_dir --chain testnet
```

**Comment by silySuper** [comment]
This log try starting the ckb process after shutting down the Neoron client on changesd port 8115?
[logs.zip](https://github.com/nervosnetwork/ckb/files/15328814/logs.zip)

**Comment by silySuper** [comment]
> > Whether we can find a faster way to solve this?because it has blocked me for about two weeks.
> 
> Do you know the absolute path of the ckb 0.114.0 binary file? Could you copy the previous `data/db` file, initialize ckb in a new directory, and try again?
> 
> 1. Initialize ckb configurations in a new_dir
> 
> ```shell
> ./ckb init -C new_dir --chain testnet
> ```
> 
> 2. copy the previous `data/db` to `new_dir/data/`
> 
> ```shell
> cp -R previous_dir/data/db new_dir/data/
> ```
> 
> 3. start the ckb
> 
> ```shell
> ./ckb run -C new_dir
> ```

Ok,I will try this

**Comment by eval-exec** [comment]
Don't delete any content from the `previous_dir`, as we still need to investigate the cause of the "CKB v114.0 Full node sync is stuck".

If you've initialized the configuration files of ckb in a new directory and it can sync smoothly with the previously copied `data/db`, it's possible that there's an issue with other temporary files in the `previous_dir`.

We can then dig into the `previous_dir` to pinpoint the problem:

1. Try moving `data/network/peer_store/addr_manager.db` elsewhere, then launch with `ckb run` to see if it works.
2. Try moving `data/network/peer_store/ban_list.db` elsewhere, then start the `ckb run` process to see if it helps.
3. Try moving `data/tx_pool` elsewhere, then start with `ckb run` to see if it makes a difference.
4. Try moving `data/indexer` elsewhere, then launch with `ckb run` to see if it works.

**Comment by silySuper** [comment]
ckb node works fine now,but neuron can not sync
<img width="559" alt="截屏2024-05-16 10 42 42" src="https://github.com/nervosnetwork/ckb/assets/25971273/fdb2058d-3005-4578-b39e-89c1dc76d352">

**Comment by eval-exec** [comment]
> but neuron can not sync

What does this mean? What did Neuron indicate? Could you try again with the `--indexer` parameter added?
```bash
./ckb run -C new_dir --indexer
```

**Comment by silySuper** [comment]
<img width="355" alt="截屏2024-05-16 10 56 10" src="https://github.com/nervosnetwork/ckb/assets/25971273/5c065823-8fb4-46fc-931b-a16c3498fb18">
Ok now

**Comment by eval-exec** [comment]
> <img alt="截屏2024-05-16 10 56 10" width="355" src="https://private-user-images.githubusercontent.com/25971273/331032628-5c065823-8fb4-46fc-931b-a16c3498fb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MjkzNjgsIm5iZiI6MTcxNTgyOTA2OCwicGF0aCI6Ii8yNTk3MTI3My8zMzEwMzI2MjgtNWMwNjU4MjMtOGZiNC00NmZjLTkzMWItYTE2YzM0OThmYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMTEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZTcwZDhlZGJjZGI4N2VmZGYyMTA5NTlmMmZmNjI5ODYzODk2Y2QwNDIyOGE5YTkxM2I5ZmZlZDBkNjhmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zmddygKFpOqOryMIOmD2qiXZBlKPDSdZmyRyweYZUck"> Ok now


It appears that the Neuron client isn't connecting to the ckb process you started in `new_dir`. In your `new_dir`, the latest tip block should be higher than 13,245,789, but the Neuron client is showing "Block Synced is 24,584."

**Comment by silySuper** [comment]
yes,but my port is same to ckb.toml
_ ./ckb run -C /Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork --indexer

**Comment by silySuper** [comment]
<img width="1274" alt="截屏2024-05-16 11 38 11" src="https://github.com/nervosnetwork/ckb/assets/25971273/863e13b2-77b6-423a-bc9b-d940eb3eeba5">
this is lateset node log

**Comment by eval-exec** [comment]
> <img alt="截屏2024-05-16 10 56 10" width="355" src="https://private-user-images.githubusercontent.com/25971273/331032628-5c065823-8fb4-46fc-931b-a16c3498fb18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzEwODksIm5iZiI6MTcxNTgzMDc4OSwicGF0aCI6Ii8yNTk3MTI3My8zMzEwMzI2MjgtNWMwNjU4MjMtOGZiNC00NmZjLTkzMWItYTE2YzM0OThmYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzMzk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2MzODZjYjJjMWEyYWZjOWFmNzBhMjRiMDhhOGM4MDY3YzBkOTBhYjE4MGI5NzVlODc1NzAwYjFiMThlNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sep5m3m6IiJa4E_Ql4FyElWcR5jxDSD5SFmWiwz-ukk"> Ok now

What Neuron's sync progress now?

**Comment by silySuper** [comment]
<img width="338" alt="截屏2024-05-16 11 41 55" src="https://github.com/nervosnetwork/ckb/assets/25971273/52bc424d-5824-43a9-ba7e-c473ed5e363e">

**Comment by eval-exec** [comment]
> <img alt="截屏2024-05-16 11 41 55" width="338" src="https://private-user-images.githubusercontent.com/25971273/331041181-52bc424d-5824-43a9-ba7e-c473ed5e363e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU4MzEyMjgsIm5iZiI6MTcxNTgzMDkyOCwicGF0aCI6Ii8yNTk3MTI3My8zMzEwNDExODEtNTJiYzQyNGQtNTgyNC00M2E5LWJhN2UtYzQ3M2VkNWUzNjNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE2VDAzNDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4M2Q2ODNhOTgzMjkxOWJjMjRhNDZhMTQzMWM1YTdiMDExMDZmN2Q4Y2VlMjNmYzhlZmE2OGJiMzA4YTNhZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.85fgliLLl89LWdfe1AQ6kQ0K8EGKea6PHQdK9pYIwKo">

Could you run the command `ps -eF | grep ckb` to check if there are two ckb nodes running on your local machine? I suspect the ckb node that Neuron is connecting to is not the one you're running in `/Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork`.

**Comment by silySuper** [comment]
<img width="559" alt="截屏2024-05-16 11 44 40" src="https://github.com/nervosnetwork/ckb/assets/25971273/c71daf11-4acb-42a4-839c-8d344810a309">

**Comment by eval-exec** [comment]
It appears the sync progress that Neuron displays pertains to the Indexer.

Previously, you only copied `data/db` from `previous_dir` to `/Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork`, which doesn't include the Indexer's data.

Now, you can move the Indexer data that has already synced to 10.63% in `/Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork` to another location:

```bash
mv  /Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork/data/indexer  backup_indexer
```

Then, move `data/indexer` from `previous_dir` to `/Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork`:

```bash
mv previous_dir/data/indexer /Volumes/My\ Passport/ckb_v0.114.0_aarch64-apple-darwin-portable/testnetwork/data
```

Restart the ckb node and then check the sync progress in Neuron. It should now show over 90%.

**Comment by silySuper** [comment]
<img width="1169" alt="截屏2024-05-16 12 04 37" src="https://github.com/nervosnetwork/ckb/assets/25971273/f4bee865-c841-4c32-a547-a304a9436c4f">
OK now

**Comment by eval-exec** [comment]
> Whether we can find a faster way to solve this? Because it has blocked me for about two weeks.

That's great, you can continue working on this testnet node.

If you are not busy next, shall we continue to investigate the root cause of the sync being stuck? https://github.com/nervosnetwork/ckb/issues/4462#issuecomment-2113895635.

**Comment by silySuper** [comment]
ok,no problem.

**Comment by silySuper** [comment]
after run for a while ,it shows zsh: Input/output error: ./ckb
<img width="574" alt="截屏2024-05-16 14 25 01" src="https://github.com/nervosnetwork/ckb/assets/25971273/725f2041-89fc-4dfc-ae7a-098e41614099">

**Comment by silySuper** [comment]
It is the hard disk no react that cause the problem.Because I find that hard disk is null,when I Disconnect and reconnect,it is ok

**Comment by 15168316096** [comment]
Since the full node is started, the previous verification was on a Mac machine and a solid-state drive environment and no related problems were encountered. Can you provide your local system environment for starting the neuron wallet, such as the version of neuron? and macos system version and SSD information

**Comment by eval-exec** [comment]
> It is the hard disk no react that cause the problem.Because I find that hard disk is null,when I Disconnect and reconnect,it is ok

Hello. Has this issue not recurred since you reconnected the hard drive? Are you able to reproduce this problem in your original environment again?
