### ISSUE TITLE
`sync_state` returns data is never updated on devnet

### ISSUE THREAD

**Issue by devchenyan** [nervosnetwork/ckb#4472]
## Bug Report

The data `sync_state` returned never changed on devnet 

### Current Behavior

Each request for `sync_state` returns the same result each time the ckb devnet node is started, with no updates to best_known_block_number, etc.

```
curl -X POST http://127.0.0.1:8114 \
-H 'Content-Type: application/json' \
-d '{ "id": 42, "jsonrpc": "2.0", "method": "sync_state", "params": [ ] }'

{"jsonrpc":"2.0","result":{"best_known_block_number":"0x42fa","best_known_block_timestamp":"0x18fc3f6de71","fast_time":"0x3e8","ibd":false,"inflight_blocks_count":"0x0","low_time":"0x5dc","normal_time":"0x4e2","orphan_blocks_count":"0x0"},"id":42}%

curl -X POST http://127.0.0.1:8114 \
-H 'Content-Type: application/json' \
-d '{ "id": 42, "jsonrpc": "2.0", "method": "sync_state", "params": [ ] }'

{"jsonrpc":"2.0","result":{"best_known_block_number":"0x42fa","best_known_block_timestamp":"0x18fc3f6de71","fast_time":"0x3e8","ibd":false,"inflight_blocks_count":"0x0","low_time":"0x5dc","normal_time":"0x4e2","orphan_blocks_count":"0x0"},"id":42}%

curl -X POST http://127.0.0.1:8114 \
-H 'Content-Type: application/json' \
-d '{ "id": 42, "jsonrpc": "2.0", "method": "sync_state", "params": [ ] }'

{"jsonrpc":"2.0","result":{"best_known_block_number":"0x42fa","best_known_block_timestamp":"0x18fc3f6de71","fast_time":"0x3e8","ibd":false,"inflight_blocks_count":"0x0","low_time":"0x5dc","normal_time":"0x4e2","orphan_blocks_count":"0x0"},"id":42}%
```

The result returned by the `sync_state` request is only updated after restarting the ckb devnet node

```
curl -X POST http://127.0.0.1:8114 \
-H 'Content-Type: application/json' \
-d '{ "id": 42, "jsonrpc": "2.0", "method": "sync_state", "params": [ ] }'

{"jsonrpc":"2.0","result":{"best_known_block_number":"0x438e","best_known_block_timestamp":"0x18fdbf5558b","fast_time":"0x3e8","ibd":false,"inflight_blocks_count":"0x0","low_time":"0x5dc","normal_time":"0x4e2","orphan_blocks_count":"0x0"},"id":42}%
```

### Expected Behavior

After starting the ckb devnet node, the results returned by the a request can be updated normally

### Environment

- **CKB version**: 0.114.0 (0c8711e 2024-02-29)
- **Chain**: dev
- **Operating system**: macOS 13.6
- **Arch**: arm64
- **Installation**: GitHub Release

**Comment by Danie0918** [comment]
@eval-exec Can you help with this?

**Comment by quake** [comment]
did you start a miner and mined new block successfully for this dev node?

**Comment by driftluo** [comment]
`sync state` only init with local on start, and will update on sync with other node, never with self mined, I think this is the reason. dev node never has network communicate

**Comment by eval-exec** [comment]
The purpose of `best_known_block_number` is to show which block with the highest `total_difficulty` among all peers connected to the current CKB node. Since the `devchain` you are running locally does not establish connections with other peers in the network, this value will not be updated.

**Comment by devchenyan** [comment]
> did you start a miner and mined new block successfully for this dev node?

yes
