### ISSUE TITLE
Performance issue about websocket of CKB node

### ISSUE THREAD

**Issue by Keith-CY** [nervosnetwork/ckb#4489]
### Current Behavior
Recently we have done a test about fee rate estimation. During the test, numerous transactions(40k+) have been submitted onto the chain and the tx pool is full of pending transactions(30k+) according to the RPC `get_raw_tx_pool`.

Our app subscribes to the CKB node via WebSocket, and pending transactions are expected to be pushed to our end. However, only 3k transactions had been received during the test, and the rest were reached in blocks.

Here's our question, is there a limit on the number of transactions pushed by WebSocket?

### Expected Behavior
Most/all pending transactions should be pushed via WebSocket.

### Environment

- **CKB version**: v0.116.1
- **Chain**: testnet
- **Operating system**: Ubuntu 18.0.6 LTS
- **Arch**: X86_64
- **Installation**: GitHub Release

### Additional context/Screenshots

The original issue could be found at https://github.com/Magickbase/ckb-explorer-public-issues/issues/704 and a question post could be found at https://talk.nervos.org/t/performance-issue-about-websocket-of-ckb-node/8248

After a brief inquiry, I was led to open a bug report here.

**Comment by zmcNotafraid** [comment]
Code: https://github.com/nervosnetwork/ckb-explorer/blob/develop/lib/websocket.rb

**Comment by eval-exec** [comment]
How is your CPU performance?
