### ISSUE TITLE
High-Intensity JSON RPC BatchRequest Causes Server Crash and Unpredictable Downtime

### ISSUE THREAD

**Issue by Cupnfish** [nervosnetwork/ckb#4520]
### Current Behavior
When subjected to high-intensity JSON RPC BatchRequest, the CKB node causes the entire server to crash, rendering it completely inaccessible. The crash occurs after a certain batch size threshold is exceeded, and even after stopping the requests, the server will still crash at an unpredictable time in the future.

### Expected Behavior
I expect the node to send an error message to the client when it cannot handle high-intensity batch sizes, rather than attempting to process the requests and causing the server to crash. Ideally, the node should shut down to prevent affecting the entire server.

### Environment
- **CKB version**: ckb 0.116.1 
- **Chain**: testnet, mainnet (both have experienced the issue)
- **Operating system**: Ubuntu 20.04
- **Arch**: x64
- **Installation**: GitHub Release

### Additional context/Screenshots
The issue was first observed when my indexer node encountered the bug and stopped working. I had used high-frequency batch sizes for a few seconds before stopping the requests. Approximately two hours later, the server suddenly became unresponsive.

**Comment by eval-exec** [comment]
Hello, What are the total memory, available memory, and CPU configuration of this server?

**Comment by chenyukang** [comment]
I think this PR may help to resolve this issue:
https://github.com/nervosnetwork/ckb/pull/4459

**Comment by chenyukang** [comment]
we have another working in progress PR try to limit the resource spent on heavy RPC:
https://github.com/nervosnetwork/ckb/pull/4469

**Comment by Cupnfish** [comment]
@eval-exec 

The server's configuration is not critical. Previously, the server with lower specifications would crash when the batch size reached 1000. With the current server's improved specifications, it crashes when the batch size reaches 2000. The interface causing the crash is `get_block_by_number`.

**Comment by Cupnfish** [comment]
Thank you for your efforts, @chenyukang ! We're eagerly looking forward to the launch of this feature to optimize resource usage. Currently, I've already determined the batch size that our server can tolerate, and to avoid any further crashes, I won't be conducting related tests for now. However, I believe this improvement will have a positive impact on our system, and I'm looking forward to the resolution of this issue.

**Comment by eval-exec** [comment]
@Cupnfish Could you provide the output of `free -h`?

**Comment by Cupnfish** [comment]
@eval-exec 
```
free -h
               total        used        free      shared  buff/cache   available
Mem:           125Gi       7.2Gi       2.0Gi        40Mi       117Gi       118Gi
Swap:             0B          0B          0B
```

**Comment by chenyukang** [comment]
@Cupnfish in the future release of ckb, you may also add this RPC configuration to limit the batch size of RPC request:

https://github.com/nervosnetwork/ckb/pull/4529/files#diff-d6c5e396f46525d03037cb71857d668d04802896dee4faf52caf8a1619c22b41R137
