### ISSUE TITLE
[FR] Use `test_tx_pool_accept` to validate transaction **before** signing

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb#4532]
## Feature Request

[`test_tx_pool_accept`](https://github.com/nervosnetwork/ckb/tree/develop/rpc#pool-test_tx_pool_accept) is a very welcomed new addition to the CKB node API. That said its utility is currently limited by the order in which errors are checked.

#### Is your feature request related to a problem? Please describe.
Given the current CKB node API and a cell previously collected by the Indexer, it is pretty difficult to tell if the cell is now Alive, **already** used in a tx in the tx pool or **already** dead. Even more, given a set of cells used by an unsigned transaction, it's even more difficult to understand their current state.

The introduction of `test_tx_pool_accept` makes it easier to test if all the inputs of an unsigned transaction are still Alive or Dead, but it's not able to differentiate between Alive cells that are already in the tx pool or those that are not. This depends on the order of the applied checks.

The only way to fully test if a transaction is executable is  to build the transaction, **ask the user to sign the transaction** and then finally check `test_tx_pool_accept`. At that point it's easy to differentiate between the different cell states, but this doesn't make any sense from the user perspective.

#### Describe the solution you'd like
I propose to reorder the checks executed by `test_tx_pool_accept` in a way that applies as very last the check of that leads to [TransactionFailedToVerify (-302)](https://github.com/nervosnetwork/ckb/blob/develop/enum.RPCError.html#variant.TransactionFailedToVerify). In this way the client has the possibility of understanding with the **unsigned** transaction if all the inputs are still Alive and spendable with a given `feeRate`.

This little change would make so much easier the DX for new DApps with Cell State contention.

What's your take on this?
Phroi

**Comment by quake** [comment]
@phroi please check out this PR: https://github.com/nervosnetwork/ckb/pull/4454 you may use this rpc to verify the cell is live or not (including tx pool).

**Comment by phroi** [comment]
Thanks @quake, I definitely missed this small change last time I checked the docs, my bad!! This is a perfect fit for my use-case, as I don't want my users to compete over feeRate. This is actually pretty good as the client is able to extract cell specific information, just at the cost of more API calls of course.

You may still find some value in the change that I proposed as it would allow to double check everything except validation before signing.

Nice job @eval-exec in getting this included directly in [ckb 0.117.0-rc4](https://github.com/nervosnetwork/ckb/releases/tag/v0.117.0-rc4), keep up the great work 💪

Phroi
