### ISSUE TITLE
In releases, `ckb-cli --version` doesn't contain the git commit ID.

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb#4550]
## Bug Report

In released packages, the binary of `ckb-cli` doesn't contain the git commit ID in outputs of the sub-command `--version`.
But `ckb --version` does.

### Current Behavior

Input:

```shell
./ckb  --version
./ckb-cli --version
```

Output:

```
ckb 0.117.0-rc5 (b853641 2024-07-22)
ckb-cli 1.9.0 ( )
```

### Expected Behavior

I think the behavior of both `ckb` and `ckb-cli` should be the same.

### Environment

I tested:
- [Last Pre-Release Binary](https://github.com/nervosnetwork/ckb/releases/download/v0.117.0-rc5/ckb_v0.117.0-rc5_x86_64-unknown-linux-gnu.tar.gz)
- [Last Release Binary](https://github.com/nervosnetwork/ckb/releases/download/v0.116.1/ckb_v0.116.1_x86_64-unknown-linux-gnu.tar.gz)

### Additional context/Screenshots

The issue is due to [the `ckb-cli` releases](https://github.com/nervosnetwork/ckb-cli/releases/download/v1.9.0/ckb-cli_v1.9.0_x86_64-unknown-linux-gnu.tar.gz).
The released `ckb-cli` doesn't contain git commit ID in its outputs of sub-command `--version`.

**Comment by eval-exec** [comment]
..
