### ISSUE TITLE
ckb run failed with :`Bad CPU type in executable`

### ISSUE THREAD

**Issue by yanguoyu** [nervosnetwork/ckb#4559]
### Environment

- **CKB version**: ckb 0.117.0, ckb 0.117.0-rc5, ckb 0.117.0-rc4
- **Chain**: [dev, staging, testnet, mainnet]
- **Operating system**: macOS 14.4.1
- **Arch**: x86_64
- **Installation**: GitHub Release

### Additional context/Screenshots

Ckb run failed with the error " Bad CPU type in executable"

<img width="879" alt="image" src="https://github.com/user-attachments/assets/72cf75fd-0b1c-4161-ad26-e9199e59b00d">

**Comment by eval-exec** [comment]
Does this help?
https://discussions.apple.com/thread/250777998?sortBy=rank

**Comment by doitian** [comment]
Re-uploaded, please try the new packages

- https://github.com/nervosnetwork/ckb/releases/download/v0.117.0/ckb_v0.117.0_x86_64-apple-darwin.zip
- https://github.com/nervosnetwork/ckb/releases/download/v0.117.0/ckb_v0.117.0_x86_64-apple-darwin-portable.zip

**Comment by doitian** [comment]
GitHub has deprecated macos-11. We fixed it in a wrong way by adding the label macos-11 to the macOS arm64 self runner. So the macOS x86 packages are created on the arm64 machines, which leads to invalid binaries.

This has been fixed by updating the runner label to macos-11 in all workflow files.

**Comment by yanguoyu** [comment]
> Re-uploaded, please try the new packages
> 
> * https://github.com/nervosnetwork/ckb/releases/download/v0.117.0/ckb_v0.117.0_x86_64-apple-darwin.zip
> * https://github.com/nervosnetwork/ckb/releases/download/v0.117.0/ckb_v0.117.0_x86_64-apple-darwin-portable.zip

Thanks, it works.
