### ISSUE TITLE
[BUG] `fee_rate_statistics` returns a feeRate median lower than 1000

### ISSUE THREAD

**Issue by phroi** [nervosnetwork/ckb#4646]
Currently `fee_rate_statistics` returns an apparently impossible median feeRate: `0x3b2` (946 < 1000)

To reproduce this feel free to use:

```bash
$ curl -X POST https://rpc.ankr.com/nervos_ckb -d '{"jsonrpc":"2.0","method":"get_fee_rate_statistics","params":[],"id":42}'
{"id":42,"jsonrpc":"2.0","result":{"mean":"0x25580","median":"0x3b2"}}
```

How is this possible?

Love & Peace, Phroi

**Comment by eval-exec** [comment]
This node's version is `v0.118.0-rc2`
```bash
❯ curl -s -X POST https://rpc.ankr.com/nervos_ckb -d '{"jsonrpc":"2.0","method":"local_node_info","params":[],"id":42}' | jq .result.version
"0.118.0-rc2 (921868e 2024-09-04)"
```

**Comment by phroi** [comment]
A couple minutes ago I also got this one, so it's not limited to that node/version:

```bash
$ curl -X POST https://mainnet.ckbapp.dev/ -d '{"jsonrpc":"2.0","method":"get_fee_rate_statistics","params":[],"id":42}';
{"jsonrpc":"2.0","result":{"mean":"0x25a65","median":"0x3b2"},"id":42}
```

**Comment by phroi** [comment]
By the way, in the past I got other issues with this method, so maybe it's related: https://github.com/nervosnetwork/ckb/issues/4350

**Comment by eval-exec** [comment]
Hello, I investigated and submited a PR to fix this, waiting for team members' review.
