### ISSUE TITLE
--help is missing --indexer option

### ISSUE THREAD

**Issue by Matt-RUN-CKB** [nervosnetwork/ckb#4650]
## Bug Report

minor bug report, --help for ckb is missing --indexer option as specified here

https://github.com/nervosnetwork/ckb-indexer

![image](https://github.com/user-attachments/assets/8fa8fb6a-7490-4d67-8def-13778322212e)

![image](https://github.com/user-attachments/assets/39a31b5e-d54a-4e74-ab66-dee7ec17a0b2)

**Comment by eval-exec** [comment]
I think `--indexer` should be in `ckb run --help`

**Comment by eval-exec** [comment]
![image](https://github.com/user-attachments/assets/588eb85e-8d6a-48b3-a7e8-a820b6bf4dab)

**Comment by Matt-RUN-CKB** [comment]
confirmed, thank you!
