### ISSUE TITLE
There is no ckb-cli in release for Linux arm64

### ISSUE THREAD

**Issue by chenyukang** [nervosnetwork/ckb#4745]
I download release tarball from this link: https://github.com/nervosnetwork/ckb/releases/download/v0.120.0-rc4/ckb_v0.120.0-rc4_aarch64-unknown-linux-gnu.tar.gz

There is no `ckb-cli` in it, the other tarball contain ckb-cli.

**Comment by eval-exec** [comment]
There is a SKIP_CKB_CLI: true` in `.github/workflows/package.yaml`.
