### ISSUE TITLE
The results of some tests is not deterministic

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb#527]
### Issue

These tests in my laptop can get random results:

The latest version:
https://github.com/nervosnetwork/ckb/blob/a7c27df3b8b2f7d0216b9ad0b27085d1fd1f4232/chain/src/tests/delay_verify.rs#L94
https://github.com/nervosnetwork/ckb/blob/a7c27df3b8b2f7d0216b9ad0b27085d1fd1f4232/chain/src/tests/basic.rs#L247

The second latest version:
https://github.com/nervosnetwork/ckb/blob/4a8533377c85a1594460def46a822bfd12707e3c/chain/src/tests/delay_verify.rs#L94
https://github.com/nervosnetwork/ckb/blob/4a8533377c85a1594460def46a822bfd12707e3c/chain/src/tests/basic.rs#L198

### Further

Caused by:
https://github.com/nervosnetwork/ckb/blob/ef1e7ff156e9e021f100168d89a4530f06cea0a7/verification/src/block_verifier.rs#L370-L375

I used `regex` to fix it (first commit in #528).

But, a better solution is required.

**Comment by quake** [comment]
It's deterministic, the change is from this PR:
https://github.com/nervosnetwork/ckb/pull/520/files#diff-365798ee66cdaead4971104be0b60a52L94

Before #520 , we are using a hashmap to check duplicate inputs, which will report the error index of the second duplicate transaction inputs. After refactoring, it will report the first index.

**Comment by yangby-cryptape** [comment]
But, I ran `make ci` for 63060826224aefceea7a0a085b68eae01d4a9529, again and again.

I got both two results.
