### ISSUE TITLE
Make rocksdb configurable via config file

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#55]

**Comment by doitian** [comment]
可以挑一些重要的选项方便来调整

**Comment by doitian** [comment]
研究下 rocksdb 是不是自己支持某种格式的配置文件

**Comment by doitian** [comment]
Review Log
**Last Reviewed At** — 2019-01-11

- Add options on demand, when we really need to tweak the options.
- Check whether rocksdb already supports some kind of config file.

**Comment by janx** [comment]
RocksDB already supports config file. I propose to add following options to node json and leave RocksDB options in a separate file:

```json
"db": {
    "rocksdb": "path/to/the/config/file"
}
```

**Comment by janx** [comment]
RocksDB supports config file but rust-rocksdb doesn't expose its load API. Instead, rust-rocksdb provides its own option interface. I'll add rust-rocksdb options to config file.

**Comment by zhangsoledad** [comment]
Closed by https://github.com/nervosnetwork/ckb/pull/230
