### ISSUE TITLE
Benchmark different hash functions used in hashset/hashmap

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#61]
Now fnv is used, https://github.com/shepmaster/twox-hash may be better.

Many hashmap/hashset uses H256 as the key, https://github.com/Cyan4973/xxHash is also a good candidate.

**Comment by xxuejie** [comment]
https://github.com/Amanieu/hashbrown is a new challenger in this space.

**Comment by quake** [comment]
we may consider https://github.com/paritytech/parity-common/tree/master/plain_hasher for H256 keyed Hashmap/Hashset
