### ISSUE TITLE
Static Build CKB on CentOS 7 for exchanges

### ISSUE THREAD

**Issue by puffanddmx** [nervosnetwork/ckb#626]
**centos 7 install guide**
- version : CentOS-7-x86_64-Minimal

**centos 7 local time setting**
- (#) ls /usr/share/zoneinfo/Asia
- (#) mv /etc/localtime /etc/localtime_org
- (#) ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime
- date

**cargo install**
- (#) curl https://sh.rustup.rs -sSf | sh

**cargo path setting**
- (#) vi .bash_profile
   -> export PATH="$HOME/.cargo/bin:$PATH" (path check)
- (#) source .bash_profile
- (#) which cargo
   ->/root/.cargo/bin/cargo (path check)

**clang & llvm install**
- (#) yum install centos-release-scl -y
- (#) yum install llvm-toolset-7 -y
- (#) scl enable llvm-toolset-7 bash

**gcc install**
- (#) yum install gcc-c++ -y

**openssl install**
- (#) yum install openssl-devel -y

**git install**
- (#) yum install git -y

**source download**
- (#) git clone https://github.com/nervosnetwork/ckb.git
- (#) cd ckb
- (#) git checkout master

**build**
- (#) make build

**ckb daemon file location**
- (#) cd target/release
    -> you can see the ckb daemon file. copy and run it with your working folder.

**configuration setting for dev mode**
- (#) ./ckb init
    -> ckb-miner.toml , ckb.toml created

**configuration setting for testnet mode**
- (#) ./ckb init --spec testnet
    -> ckb-miner.toml , ckb.toml created

**ckb dev mode daemon run for mining**
- (#) nohup ./ckb run &
- (#) nohup ./ckb miner &

**dev mode port**
- p2p port : 8115
- rpc port : 8114

**ckb folder structure**
- (#) yum install tree -y
- (#) tree
├── ckb
├── ckb-miner.toml
├── ckb.toml
└── data (db, logs, network)

**Comment by doitian** [comment]
Thanks for providing the information.
