### ISSUE TITLE
Adding component rustfmt on macOS fails

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb#83]
When run `rustup component add rustfmt` on macOS 10.14.1 the following error pops up:

```
toolchain '1.31.0-x86_64-apple-darwin' does not contain component 'rustfmt' for target 'x86_64-apple-darwin'
```

Same with the `clippy` component.

Adding preview version of these components succeeds.

**Comment by zhangsoledad** [comment]
https://users.rust-lang.org/t/clippy-and-rustfmt-on-stable-rust-1-31/23021
if you installed the previous toolchain, reinstall it
```
rustup self update
rustup toolchain uninstall stable
rustup toolchain install stable
```
notice: unset current override

**Comment by ashchan** [comment]
OK so this a rustup. The above commands didn't solve my issue but I'll try reinstalling rust completely.
