### ISSUE TITLE
Allow miner add an arbitrary message into the cellbase

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#888]
Miner can fill any data into the cellbase output cell data. It can be a part of the block assembler config

**Comment by janx** [comment]
We don't need to use first arg for block number as we already have it in header.

**Comment by doitian** [comment]
> We don't need to use first arg for block number as we already have it in header.

This rule ensure every tx has a unique tx hash, otherwise, cellbase may have duplicated tx hash.

**Comment by janx** [comment]
How about require the cellbase input use its own header as outpoint?

**Comment by janx** [comment]
Input args will be removed soon, how about add a header dep refering to its own header to guarantee unique tx hash?

**Comment by doitian** [comment]
Blocked by https://github.com/nervosnetwork/ckb/issues/913

**Comment by doitian** [comment]
> Blocked by https://github.com/nervosnetwork/ckb/issues/913

We'll use cell data for this future
