### ISSUE TITLE
Should not use same struct for both storage and core logic in all cases

### ISSUE THREAD

**Issue by yangby-cryptape** [nervosnetwork/ckb#892]
For example:

This is the definition of `CellMeta`:
https://github.com/nervosnetwork/ckb/blob/e09eca6ae2eba520ade4b4fc4e20538517c73148/core/src/cell.rs#L25-L33

The `CellMeta` is saved into storage **with three `Option` fields** (bring uncertainty into storage):
https://github.com/nervosnetwork/ckb/blob/e09eca6ae2eba520ade4b4fc4e20538517c73148/store/src/store.rs#L465-L475

Most fields in the `CellMeta` are **redundant**, and I've heard that some guys want to **add more fileds into this struct**.

This struct likes a virus, some methods have to set `None` when build it and `unwrap` before use it (or just skip handle the cases when `is_none()`).

This style makes it to be hard to implement a robust program.

**Comment by doitian** [comment]
We even have a `#[serde(skip)]` field here. 😱

**Comment by janx** [comment]
Can we list the features depending on this struct? Once we get those features done we can start refactoring.
