### ISSUE TITLE
Static link OpenSSL

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb#902]
I have tried in Ubuntu Xenial:

```
export OPENSSL_STATIC=1 OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCLUDE_DIR=/usr/include/openssl
```

The last linking command will raise an error like:

```
relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

In Centos 7, I got some other errors that missing symbols related to krb5. I have tried adding `OPENSSL_NO_KRB` flags but had no luck.

**Comment by apiraino** [comment]
Hi @doitian!

I've dug a little bit (I also had issues with compiling a custom version of OpenSSL), you might want to try the following.

First download and compile latest OpenSSL (1.1.1b as of yet)

```
$ wget https://www.openssl.org/source/openssl-1.1.1b.tar.gz 
$ tar xvzf openssl-1.1.1b.tar.gz && cd openssl
$ ./config -fPIC && make
```

Then compile CKB against the local OpenSSL lib (we don't need any `-dev` package from the operating system)
```
$ cat build.sh
export OPENSSL_STATIC=yes
BASE_PATH=/path/to/compiled/openssl
export OPENSSL_LIB_DIR=$BASE_PATH/openssl-1.1.1b
export OPENSSL_INCLUDE_DIR=$OPENSSL_LIB_DIR/include
make prod
```

Now the compiled CKB binary does not show anymore being linked to OpenSSL lib:
```
$ ldd target/release/ckb | grep "ssl\|crypto"
$
```


Tested on Ubuntu 19.04 and 16.04 LTS 

Useful references: [here](https://github.com/sfackler/rust-openssl/issues/183#issuecomment-81686336) and [here](https://github.com/rust-lang/cargo/issues/713#issuecomment-59597433)

**Comment by doitian** [comment]
Thanks for providing the info. I was going to follow your instructions, but it turned out that the static link just works in Bionic using `libssl-dev`.

**Comment by TheWaWaR** [comment]
Maybe we can learn from `sentry-cli`:
* https://github.com/getsentry/sentry-cli/blob/master/Dockerfile
* https://github.com/getsentry/rust-musl-cross/blob/master/Dockerfile

**Comment by gliheng** [comment]
I'm on windows and it turned out static linking does not work even with OPENSSL_DIR, OPENSSL_LIB_DIR, OPENSSL_INCLUDE_DIR, OPENSSL_STATIC set
