### ISSUE TITLE
CKB supported on windows, finally succeed!

### ISSUE THREAD

**Issue by mohanson** [nervosnetwork/ckb#934]
![img](http://api.accu.cc:81/22.png)

In short, we must install **visual studio c build tools** and **llvm**, and fix compatibility  of dependency **blake2b-rs**, **rocksdb** and **ckb-vm**.

1. Update the **blake2b-rs** to the latest, I spent a day fixing the problem with this library, but found that you are already done, sad
2. About, **ckb-vm**, close the feature "asm", that's worked...
3. About **librocksdb-sys**, emmm, it's damn complex, although the official said that it does not support windows, there are still ways to compile normally.
    1. Install **Build Tools for Visual Studio 2019**, from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017
    2. Install **LLVM**, from http://releases.llvm.org/download.html, **Windows (64-bit) (.sig)**
    3. SET the env, like **LIBCLANG_PATH="C:\MyApp\LLVM\lib"**

4. Then **cargo build**, and drinking a cup of tea at the same time

**Comment by doitian** [comment]
Thanks for providing the info. Now CKB can work in Windows, and we have setup azure pipelines to run tests and create package on Windows.
