### ISSUE TITLE
Is Miner RPC method submit_block supposed to be called directly

### ISSUE THREAD

**Issue by ashchan** [nervosnetwork/ckb#94]
Is `submit_block` supposed to be called by any SDK client?

The inline example with the RPC method implementation doesn't work due to the lack of required elements for `header`. (`raw` and `seal` respectively).

> curl -d '{"id": 2, "jsonrpc": "2.0", "method":"submit_block","params": [{"header":{}, "uncles":[], "commit_transactions":[], "proposal_transactions":[]}]}' -H 'content-type:application/json' 'http://localhost:8114'

**Comment by doitian** [comment]
No, `submit_block` and `get_blocktemplate` are only for miner implemention.
